
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-15T11:44:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cca012876af9ac6562f53e3a4de54aeea5a68db",
 "version": "2021.3.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
