
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-10T17:00:33-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "dea6358fe1bf623965d9538372c1cb5a76fd19a7",
 "version": "0.14.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
