"""
    SatNOGS DB

    SatNOGS DB is a crowdsourced database of details about orbital                     satellites and data collected from them.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Contact: dev@satnogs.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import satnogsdbapiclient
from satnogsdbapiclient.api.satellites_api import SatellitesApi  # noqa: E501


class TestSatellitesApi(unittest.TestCase):
    """SatellitesApi unit test stubs"""

    def setUp(self):
        self.api = SatellitesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_satellites_list(self):
        """Test case for satellites_list

        """
        pass

    def test_satellites_retrieve(self):
        """Test case for satellites_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
