JSON_CONTENT_TYPE = {'ContentType': 'application/json'}

OK_CODE = 200
VALIDATION_ERROR_CODE = 400
UNAUTHORISED_ERROR_CODE = 401
FORBIDDEN_ERROR_CODE = 403
NOT_FOUND_ERROR_CODE = 404
METHOD_NOT_ALLOWED_ERROR_CODE = 405
BAD_GATEWAY_ERROR_CODE = 502
GATEWAY_TIMEOUT_ERROR_CODE = 504
SERVICE_NOT_AVAILABLE_ERROR_CODE = 503
GENERAL_SERVICE_ERROR_CODE = 500
