# Generated by Django 3.1.5 on 2021-01-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0003_description_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='sequenceRef',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
