
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-17T16:44:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f32e55e137c63d0278d0b664e49afd6b0bf7156",
 "version": "2021.3.17.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
