# coding: utf-8

"""
    Nomad Hawk

    This is the API descriptor for the Nomad Hawk API, responsible for tracking and analytics.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import nomad_hawk_cli
from nomad_hawk_cli.models.api_response_data import ApiResponseData  # noqa: E501
from nomad_hawk_cli.rest import ApiException

class TestApiResponseData(unittest.TestCase):
    """ApiResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = nomad_hawk_cli.models.api_response_data.ApiResponseData()  # noqa: E501
        if include_optional :
            return ApiResponseData(
                foobar = '0'
            )
        else :
            return ApiResponseData(
        )

    def testApiResponseData(self):
        """Test ApiResponseData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
