# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61968/assets/Structure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61968.assets import AssetContainer_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61968_dot_assets_dot_AssetContainer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/protobuf/cim/iec61968/assets/Structure.proto',
  package='zepben.protobuf.cim.iec61968.assets',
  syntax='proto3',
  serialized_options=b'\n\'com.zepben.protobuf.cim.iec61968.assetsP\001\252\002#Zepben.Protobuf.CIM.IEC61968.Assets',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3zepben/protobuf/cim/iec61968/assets/Structure.proto\x12#zepben.protobuf.cim.iec61968.assets\x1a\x38zepben/protobuf/cim/iec61968/assets/AssetContainer.proto\"L\n\tStructure\x12?\n\x02\x61\x63\x18\x01 \x01(\x0b\x32\x33.zepben.protobuf.cim.iec61968.assets.AssetContainerBQ\n\'com.zepben.protobuf.cim.iec61968.assetsP\x01\xaa\x02#Zepben.Protobuf.CIM.IEC61968.Assetsb\x06proto3'
  ,
  dependencies=[zepben_dot_protobuf_dot_cim_dot_iec61968_dot_assets_dot_AssetContainer__pb2.DESCRIPTOR,])




_STRUCTURE = _descriptor.Descriptor(
  name='Structure',
  full_name='zepben.protobuf.cim.iec61968.assets.Structure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ac', full_name='zepben.protobuf.cim.iec61968.assets.Structure.ac', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=226,
)

_STRUCTURE.fields_by_name['ac'].message_type = zepben_dot_protobuf_dot_cim_dot_iec61968_dot_assets_dot_AssetContainer__pb2._ASSETCONTAINER
DESCRIPTOR.message_types_by_name['Structure'] = _STRUCTURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Structure = _reflection.GeneratedProtocolMessageType('Structure', (_message.Message,), {
  'DESCRIPTOR' : _STRUCTURE,
  '__module__' : 'zepben.protobuf.cim.iec61968.assets.Structure_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.cim.iec61968.assets.Structure)
  })
_sym_db.RegisterMessage(Structure)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
