
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-09T21:05:25-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2229d46c422961e259768a209bbbc75264f9ea4c",
 "version": "v1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
