# Generated by Django 1.11.29 on 2020-04-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_increase_char_limit_on_transmitter_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='transmitter_mode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
