# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosdyn/api/graph_nav/recording_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api.graph_nav import recording_pb2 as bosdyn_dot_api_dot_graph__nav_dot_recording__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bosdyn/api/graph_nav/recording_service.proto',
  package='bosdyn.api.graph_nav',
  syntax='proto3',
  serialized_pb=_b('\n,bosdyn/api/graph_nav/recording_service.proto\x12\x14\x62osdyn.api.graph_nav\x1a$bosdyn/api/graph_nav/recording.proto2\xc4\x05\n\x18GraphNavRecordingService\x12m\n\x0eStartRecording\x12+.bosdyn.api.graph_nav.StartRecordingRequest\x1a,.bosdyn.api.graph_nav.StartRecordingResponse\"\x00\x12j\n\rStopRecording\x12*.bosdyn.api.graph_nav.StopRecordingRequest\x1a+.bosdyn.api.graph_nav.StopRecordingResponse\"\x00\x12m\n\x0e\x43reateWaypoint\x12+.bosdyn.api.graph_nav.CreateWaypointRequest\x1a,.bosdyn.api.graph_nav.CreateWaypointResponse\"\x00\x12\x88\x01\n\x17SetRecordingEnvironment\x12\x34.bosdyn.api.graph_nav.SetRecordingEnvironmentRequest\x1a\x35.bosdyn.api.graph_nav.SetRecordingEnvironmentResponse\"\x00\x12\x61\n\nCreateEdge\x12\'.bosdyn.api.graph_nav.CreateEdgeRequest\x1a(.bosdyn.api.graph_nav.CreateEdgeResponse\"\x00\x12p\n\x0fGetRecordStatus\x12,.bosdyn.api.graph_nav.GetRecordStatusRequest\x1a-.bosdyn.api.graph_nav.GetRecordStatusResponse\"\x00\x42\x17\x42\x15RecordingServiceProtob\x06proto3')
  ,
  dependencies=[bosdyn_dot_api_dot_graph__nav_dot_recording__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\025RecordingServiceProto'))

_GRAPHNAVRECORDINGSERVICE = _descriptor.ServiceDescriptor(
  name='GraphNavRecordingService',
  full_name='bosdyn.api.graph_nav.GraphNavRecordingService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=109,
  serialized_end=817,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartRecording',
    full_name='bosdyn.api.graph_nav.GraphNavRecordingService.StartRecording',
    index=0,
    containing_service=None,
    input_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._STARTRECORDINGREQUEST,
    output_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._STARTRECORDINGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopRecording',
    full_name='bosdyn.api.graph_nav.GraphNavRecordingService.StopRecording',
    index=1,
    containing_service=None,
    input_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._STOPRECORDINGREQUEST,
    output_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._STOPRECORDINGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateWaypoint',
    full_name='bosdyn.api.graph_nav.GraphNavRecordingService.CreateWaypoint',
    index=2,
    containing_service=None,
    input_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._CREATEWAYPOINTREQUEST,
    output_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._CREATEWAYPOINTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetRecordingEnvironment',
    full_name='bosdyn.api.graph_nav.GraphNavRecordingService.SetRecordingEnvironment',
    index=3,
    containing_service=None,
    input_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._SETRECORDINGENVIRONMENTREQUEST,
    output_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._SETRECORDINGENVIRONMENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateEdge',
    full_name='bosdyn.api.graph_nav.GraphNavRecordingService.CreateEdge',
    index=4,
    containing_service=None,
    input_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._CREATEEDGEREQUEST,
    output_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._CREATEEDGERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRecordStatus',
    full_name='bosdyn.api.graph_nav.GraphNavRecordingService.GetRecordStatus',
    index=5,
    containing_service=None,
    input_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._GETRECORDSTATUSREQUEST,
    output_type=bosdyn_dot_api_dot_graph__nav_dot_recording__pb2._GETRECORDSTATUSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRAPHNAVRECORDINGSERVICE)

DESCRIPTOR.services_by_name['GraphNavRecordingService'] = _GRAPHNAVRECORDINGSERVICE

# @@protoc_insertion_point(module_scope)
