# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cognite/seismic/protos/ingest_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from cognite.seismic.protos import ingest_service_messages_pb2 as cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cognite/seismic/protos/ingest_service.proto',
  package='com.cognite.seismic',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+cognite/seismic/protos/ingest_service.proto\x12\x13\x63om.cognite.seismic\x1a\x1bgoogle/protobuf/empty.proto\x1a\x34\x63ognite/seismic/protos/ingest_service_messages.proto2\x84\x08\n\x06Ingest\x12k\n\x0eRegisterSurvey\x12*.com.cognite.seismic.RegisterSurveyRequest\x1a+.com.cognite.seismic.RegisterSurveyResponse\"\x00\x12\x65\n\x0cRegisterFile\x12(.com.cognite.seismic.RegisterFileRequest\x1a).com.cognite.seismic.RegisterFileResponse\"\x00\x12_\n\nIngestFile\x12&.com.cognite.seismic.IngestFileRequest\x1a\'.com.cognite.seismic.IngestFileResponse\"\x00\x12S\n\x06Status\x12\".com.cognite.seismic.StatusRequest\x1a#.com.cognite.seismic.StatusResponse\"\x00\x12N\n\nDeleteFile\x12&.com.cognite.seismic.DeleteFileRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n\x0c\x44\x65leteSurvey\x12(.com.cognite.seismic.DeleteSurveyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Y\n\x08\x45\x64itFile\x12$.com.cognite.seismic.EditFileRequest\x1a%.com.cognite.seismic.EditFileResponse\"\x00\x12_\n\nEditSurvey\x12&.com.cognite.seismic.EditSurveyRequest\x1a\'.com.cognite.seismic.EditSurveyResponse\"\x00\x12h\n\x0eListFileAccess\x12*.com.cognite.seismic.ListFileAccessRequest\x1a(.com.cognite.seismic.ProjectListResponse\"\x00\x12V\n\x0e\x45\x64itFileAccess\x12*.com.cognite.seismic.EditFileAccessRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n\nStoreTrace\x12&.com.cognite.seismic.StoreTraceRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_INGEST = _descriptor.ServiceDescriptor(
  name='Ingest',
  full_name='com.cognite.seismic.Ingest',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=152,
  serialized_end=1180,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterSurvey',
    full_name='com.cognite.seismic.Ingest.RegisterSurvey',
    index=0,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._REGISTERSURVEYREQUEST,
    output_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._REGISTERSURVEYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterFile',
    full_name='com.cognite.seismic.Ingest.RegisterFile',
    index=1,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._REGISTERFILEREQUEST,
    output_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._REGISTERFILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IngestFile',
    full_name='com.cognite.seismic.Ingest.IngestFile',
    index=2,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._INGESTFILEREQUEST,
    output_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._INGESTFILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Status',
    full_name='com.cognite.seismic.Ingest.Status',
    index=3,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._STATUSREQUEST,
    output_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteFile',
    full_name='com.cognite.seismic.Ingest.DeleteFile',
    index=4,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._DELETEFILEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteSurvey',
    full_name='com.cognite.seismic.Ingest.DeleteSurvey',
    index=5,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._DELETESURVEYREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EditFile',
    full_name='com.cognite.seismic.Ingest.EditFile',
    index=6,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._EDITFILEREQUEST,
    output_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._EDITFILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EditSurvey',
    full_name='com.cognite.seismic.Ingest.EditSurvey',
    index=7,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._EDITSURVEYREQUEST,
    output_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._EDITSURVEYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListFileAccess',
    full_name='com.cognite.seismic.Ingest.ListFileAccess',
    index=8,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._LISTFILEACCESSREQUEST,
    output_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._PROJECTLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EditFileAccess',
    full_name='com.cognite.seismic.Ingest.EditFileAccess',
    index=9,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._EDITFILEACCESSREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StoreTrace',
    full_name='com.cognite.seismic.Ingest.StoreTrace',
    index=10,
    containing_service=None,
    input_type=cognite_dot_seismic_dot_protos_dot_ingest__service__messages__pb2._STORETRACEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INGEST)

DESCRIPTOR.services_by_name['Ingest'] = _INGEST

# @@protoc_insertion_point(module_scope)
