# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosdyn/api/log_annotation_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import log_annotation_pb2 as bosdyn_dot_api_dot_log__annotation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bosdyn/api/log_annotation_service.proto',
  package='bosdyn.api',
  syntax='proto3',
  serialized_pb=_b('\n\'bosdyn/api/log_annotation_service.proto\x12\nbosdyn.api\x1a\x1f\x62osdyn/api/log_annotation.proto2w\n\x14LogAnnotationService\x12_\n\x10\x41\x64\x64LogAnnotation\x12#.bosdyn.api.AddLogAnnotationRequest\x1a$.bosdyn.api.AddLogAnnotationResponse\"\x00\x42\x1b\x42\x19LogAnnotationServiceProtob\x06proto3')
  ,
  dependencies=[bosdyn_dot_api_dot_log__annotation__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\031LogAnnotationServiceProto'))

_LOGANNOTATIONSERVICE = _descriptor.ServiceDescriptor(
  name='LogAnnotationService',
  full_name='bosdyn.api.LogAnnotationService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=88,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddLogAnnotation',
    full_name='bosdyn.api.LogAnnotationService.AddLogAnnotation',
    index=0,
    containing_service=None,
    input_type=bosdyn_dot_api_dot_log__annotation__pb2._ADDLOGANNOTATIONREQUEST,
    output_type=bosdyn_dot_api_dot_log__annotation__pb2._ADDLOGANNOTATIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGANNOTATIONSERVICE)

DESCRIPTOR.services_by_name['LogAnnotationService'] = _LOGANNOTATIONSERVICE

# @@protoc_insertion_point(module_scope)
