
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b029f4433f84399b8788131659167522dad3a826",
 "version": "2411"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
