# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/engine_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import message_pb2 as proto_dot_message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/engine_service.proto',
  package='gs.rpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aproto/engine_service.proto\x12\x06gs.rpc\x1a\x13proto/message.proto2\x8d\x01\n\rEngineService\x12:\n\x07RunStep\x12\x16.gs.rpc.RunStepRequest\x1a\x17.gs.rpc.RunStepResponse\x12@\n\tHeartBeat\x12\x18.gs.rpc.HeartBeatRequest\x1a\x19.gs.rpc.HeartBeatResponseb\x06proto3'
  ,
  dependencies=[proto_dot_message__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ENGINESERVICE = _descriptor.ServiceDescriptor(
  name='EngineService',
  full_name='gs.rpc.EngineService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=60,
  serialized_end=201,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunStep',
    full_name='gs.rpc.EngineService.RunStep',
    index=0,
    containing_service=None,
    input_type=proto_dot_message__pb2._RUNSTEPREQUEST,
    output_type=proto_dot_message__pb2._RUNSTEPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HeartBeat',
    full_name='gs.rpc.EngineService.HeartBeat',
    index=1,
    containing_service=None,
    input_type=proto_dot_message__pb2._HEARTBEATREQUEST,
    output_type=proto_dot_message__pb2._HEARTBEATRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENGINESERVICE)

DESCRIPTOR.services_by_name['EngineService'] = _ENGINESERVICE

# @@protoc_insertion_point(module_scope)
