REPORT_FILE_EXTENSION = '.json'

TESTOPS_UUID_ATTR = 'TO_UUID'

TESTOPS_SERVER_URL = 'basePath'
TESTOPS_SERVER_URL_ENV = 'TESTOPS_SERVER_URL'
TESTOPS_SERVER_URL_DEFAULT = 'https://testops.katalon.io'

TESTOPS_API_KEY = 'apiKey'
TESTOPS_API_KEY_ENV = 'TESTOPS_API_KEY'

TESTOPS_PROJECT_ID = 'projectId'
TESTOPS_PROJECT_ID_ENV = 'TESTOPS_PROJECT_ID'

TESTOPS_REPORT_FOLDER = 'reportFolder'
TESTOPS_REPORT_FOLDER_ENV = 'TESTOPS_REPORT_FOLDER'
TESTOPS_REPORT_FOLDER_DEFAULT = 'testops-report'

TESTOPS_BUILD_LABEL = 'buildLabel'
TESTOPS_BUILD_LABEL_ENV = 'TESTOPS_BUILD_LABEL'

TESTOPS_BUILD_URL = 'buildUrl'
TESTOPS_BUILD_URL_ENV = 'TESTOPS_BUILD_URL'

TESTOPS_SESSION_ID = 'sessionId'
TESTOPS_SESSION_ID_ENV = 'TESTOPS_SESSION_ID'

# proxy
TESTOPS_PROXY_SERVER_TYPE = 'proxy.protocol'
TESTOPS_PROXY_SERVER_TYPE_ENV = 'TESTOPS_PROXY_SERVER_TYPE'
TESTOPS_PROXY_SERVER_TYPE_DEFAULT = 'http'

TESTOPS_PROXY_HOST = 'proxy.host'
TESTOPS_PROXY_HOST_ENV = 'TESTOPS_PROXY_HOST'

TESTOPS_PROXY_PORT = 'proxy.port'
TESTOPS_PROXY_PORT_ENV = 'TESTOPS_PROXY_PORT'

TESTOPS_PROXY_USERNAME = 'proxy.auth.username'
TESTOPS_PROXY_USERNAME_ENV = 'TESTOPS_PROXY_USERNAME'

TESTOPS_PROXY_PASSWORD = 'proxy.auth.password'
TESTOPS_PROXY_PASSWORD_ENV = 'TESTOPS_PROXY_PASSWORD'

REPORT_PATTERN = r'.*(?i)\.json'
