('any_pb2', 'Any',
[
'Pack',
'Unpack',
'TypeName',
'Is',
]),
('timestamp_pb2', 'Timestamp',
[
'ToJsonString',
'FromJsonString',
'GetCurrentTime',
'ToNanoseconds',
'ToMicroseconds',
'ToMilliseconds',
'ToSeconds',
'FromNanoseconds',
'FromMicroseconds',
'FromMilliseconds',
'FromSeconds',
'ToDatetime',
'FromDatetime',
]),
('duration_pb2', 'Duration',
[
'ToJsonString',
'FromJsonString',
'ToNanoseconds',
'ToMicroseconds',
'ToMilliseconds',
'ToSeconds',
'FromNanoseconds',
'FromMicroseconds',
'FromMilliseconds',
'FromSeconds',
'ToTimedelta',
'FromTimedelta',
]),
('fieldmask_pb2', 'FieldMask',
[
'ToJsonString',
'FromJsonString',
'IsValidForDescriptor',
'AllFieldsFromDescriptor',
'CanonicalFormFromMask',
'Union',
'Intersect',
'MergeMessage',
]),
('_fieldmasktree_pb2', '_FieldMaskTree',
[
'MergeFromFieldMask',
'AddPath',
'ToFieldMask',
'IntersectPath',
'AddLeafNodes',
'MergeMessage',
]),
('struct_pb2', 'Struct',
[
'keys',
'values',
'items',
'get_or_create_list',
'get_or_create_struct',
'update',
]),
('listvalue_pb2', 'ListValue',
[
'append',
'extend',
'items',
'add_struct',
'add_list',
])
