
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-11T04:58:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2653c05a239b921d7e8223ae4ff6b95e4e74e430",
 "version": "1.15.0.post.dev77"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
