"""
    SatNOGS DB

    SatNOGS DB is a crowdsourced database of details about orbital                     satellites and data collected from them.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Contact: dev@satnogs.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import satnogsdbapiclient
from satnogsdbapiclient.model.sat_telemetry import SatTelemetry


class TestSatTelemetry(unittest.TestCase):
    """SatTelemetry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSatTelemetry(self):
        """Test SatTelemetry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SatTelemetry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
