# Generated by Django 1.10.5 on 2017-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20160508_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='waterfall',
            field=models.ImageField(blank=True, null=True, upload_to='data_waterfalls'),
        ),
    ]
