# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61970/base/wires/generation/production/PowerElectronicsUnit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61970.base.core import Equipment_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_core_dot_Equipment__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/protobuf/cim/iec61970/base/wires/generation/production/PowerElectronicsUnit.proto',
  package='zepben.protobuf.cim.iec61970.base.wires.generation.production',
  syntax='proto3',
  serialized_options=b'\nAcom.zepben.protobuf.cim.iec61970.base.wires.generation.productionP\001\252\002=Zepben.Protobuf.CIM.IEC61970.Base.Wires.Generation.Production',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nXzepben/protobuf/cim/iec61970/base/wires/generation/production/PowerElectronicsUnit.proto\x12=zepben.protobuf.cim.iec61970.base.wires.generation.production\x1a\x36zepben/protobuf/cim/iec61970/base/core/Equipment.proto\"\x99\x01\n\x14PowerElectronicsUnit\x12=\n\x02\x65q\x18\x01 \x01(\x0b\x32\x31.zepben.protobuf.cim.iec61970.base.core.Equipment\x12\x0c\n\x04maxP\x18\x02 \x01(\x05\x12\x0c\n\x04minP\x18\x03 \x01(\x05\x12&\n\x1epowerElectronicsConnectionMRID\x18\x04 \x01(\tB\x85\x01\nAcom.zepben.protobuf.cim.iec61970.base.wires.generation.productionP\x01\xaa\x02=Zepben.Protobuf.CIM.IEC61970.Base.Wires.Generation.Productionb\x06proto3'
  ,
  dependencies=[zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_core_dot_Equipment__pb2.DESCRIPTOR,])




_POWERELECTRONICSUNIT = _descriptor.Descriptor(
  name='PowerElectronicsUnit',
  full_name='zepben.protobuf.cim.iec61970.base.wires.generation.production.PowerElectronicsUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='eq', full_name='zepben.protobuf.cim.iec61970.base.wires.generation.production.PowerElectronicsUnit.eq', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxP', full_name='zepben.protobuf.cim.iec61970.base.wires.generation.production.PowerElectronicsUnit.maxP', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minP', full_name='zepben.protobuf.cim.iec61970.base.wires.generation.production.PowerElectronicsUnit.minP', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='powerElectronicsConnectionMRID', full_name='zepben.protobuf.cim.iec61970.base.wires.generation.production.PowerElectronicsUnit.powerElectronicsConnectionMRID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=365,
)

_POWERELECTRONICSUNIT.fields_by_name['eq'].message_type = zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_core_dot_Equipment__pb2._EQUIPMENT
DESCRIPTOR.message_types_by_name['PowerElectronicsUnit'] = _POWERELECTRONICSUNIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerElectronicsUnit = _reflection.GeneratedProtocolMessageType('PowerElectronicsUnit', (_message.Message,), {
  'DESCRIPTOR' : _POWERELECTRONICSUNIT,
  '__module__' : 'zepben.protobuf.cim.iec61970.base.wires.generation.production.PowerElectronicsUnit_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.cim.iec61970.base.wires.generation.production.PowerElectronicsUnit)
  })
_sym_db.RegisterMessage(PowerElectronicsUnit)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
