# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61968/assets/StreetlightLampKind.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/protobuf/cim/iec61968/assets/StreetlightLampKind.proto',
  package='zepben.protobuf.cim.iec61968.assets',
  syntax='proto3',
  serialized_options=b'\n\'com.zepben.protobuf.cim.iec61968.assetsP\001\252\002#Zepben.Protobuf.CIM.IEC61968.Assets',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n=zepben/protobuf/cim/iec61968/assets/StreetlightLampKind.proto\x12#zepben.protobuf.cim.iec61968.assets*l\n\x13StreetlightLampKind\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x18\n\x14HIGH_PRESSURE_SODIUM\x10\x01\x12\x11\n\rMERCURY_VAPOR\x10\x02\x12\x10\n\x0cMETAL_HALIDE\x10\x03\x12\t\n\x05OTHER\x10\x04\x42Q\n\'com.zepben.protobuf.cim.iec61968.assetsP\x01\xaa\x02#Zepben.Protobuf.CIM.IEC61968.Assetsb\x06proto3'
)

_STREETLIGHTLAMPKIND = _descriptor.EnumDescriptor(
  name='StreetlightLampKind',
  full_name='zepben.protobuf.cim.iec61968.assets.StreetlightLampKind',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HIGH_PRESSURE_SODIUM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MERCURY_VAPOR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='METAL_HALIDE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=102,
  serialized_end=210,
)
_sym_db.RegisterEnumDescriptor(_STREETLIGHTLAMPKIND)

StreetlightLampKind = enum_type_wrapper.EnumTypeWrapper(_STREETLIGHTLAMPKIND)
UNKNOWN = 0
HIGH_PRESSURE_SODIUM = 1
MERCURY_VAPOR = 2
METAL_HALIDE = 3
OTHER = 4


DESCRIPTOR.enum_types_by_name['StreetlightLampKind'] = _STREETLIGHTLAMPKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
