# Generated by Django 2.2.14 on 2020-09-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_tle_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestTleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('latest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest', to='base.Tle')),
                ('latest_distributable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_distributable', to='base.Tle')),
                ('satellite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_tle_set', to='base.Satellite')),
            ],
        ),
        migrations.DeleteModel(
            name='LatestTle',
        ),
    ]
