# Generated by Django 3.1.5 on 2021-03-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_rename_user_field_on_transmitter_entry_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transmitterentry',
            old_name='reviewed',
            new_name='is_reviewed',
        ),
    ]
