# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matialvarezs_grafana_customers', '0004_panelsbyrowdashboardgrafana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelsbyrowdashboardgrafana',
            old_name='row_conent',
            new_name='row_content',
        ),
    ]
