# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61968/common/Organisation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61970.base.core import IdentifiedObject_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_core_dot_IdentifiedObject__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/protobuf/cim/iec61968/common/Organisation.proto',
  package='zepben.protobuf.cim.iec61968.common',
  syntax='proto3',
  serialized_options=b'\n\'com.zepben.protobuf.cim.iec61968.commonP\001\252\002#Zepben.Protobuf.CIM.IEC61968.Common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6zepben/protobuf/cim/iec61968/common/Organisation.proto\x12#zepben.protobuf.cim.iec61968.common\x1a=zepben/protobuf/cim/iec61970/base/core/IdentifiedObject.proto\"T\n\x0cOrganisation\x12\x44\n\x02io\x18\x01 \x01(\x0b\x32\x38.zepben.protobuf.cim.iec61970.base.core.IdentifiedObjectBQ\n\'com.zepben.protobuf.cim.iec61968.commonP\x01\xaa\x02#Zepben.Protobuf.CIM.IEC61968.Commonb\x06proto3'
  ,
  dependencies=[zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_core_dot_IdentifiedObject__pb2.DESCRIPTOR,])




_ORGANISATION = _descriptor.Descriptor(
  name='Organisation',
  full_name='zepben.protobuf.cim.iec61968.common.Organisation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='io', full_name='zepben.protobuf.cim.iec61968.common.Organisation.io', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=242,
)

_ORGANISATION.fields_by_name['io'].message_type = zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_core_dot_IdentifiedObject__pb2._IDENTIFIEDOBJECT
DESCRIPTOR.message_types_by_name['Organisation'] = _ORGANISATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Organisation = _reflection.GeneratedProtocolMessageType('Organisation', (_message.Message,), {
  'DESCRIPTOR' : _ORGANISATION,
  '__module__' : 'zepben.protobuf.cim.iec61968.common.Organisation_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.cim.iec61968.common.Organisation)
  })
_sym_db.RegisterMessage(Organisation)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
