from enum import Enum
from typing import Any

NCS2_VID: int
NCS2_PID: int
CUDA_SUPPORTED_BOARDS: Any
TEGRA_CHIP_PATH: str
MYRIAD_SUPPORTED_OS: Any
EYECLOUD_SUPPORTED_MODEL_PURPOSES: Any

class Engine(Enum):
    DNN: str = ...
    DNN_OPENVINO: str = ...
    DNN_CUDA: str = ...
    TENSOR_RT: str = ...

class Accelerator(Enum):
    DEFAULT: str = ...
    CPU: str = ...
    GPU: str = ...
    MYRIAD: str = ...
    NVIDIA: str = ...
    NVIDIA_FP16: str = ...
