from edgeiq import edge_tools as edge_tools, processing as processing
from edgeiq.base_service import BaseService as BaseService
from typing import Any, Optional

class Pose:
    def __init__(self, key_points: Any, score: Any) -> None: ...
    @property
    def key_points(self): ...
    @property
    def score(self): ...

class HumanPoseResult:
    def __init__(self, poses: Any, image: Any, input_dimension: Any, start: Any, end: Any, **kwargs: Any) -> None: ...
    @property
    def image(self): ...
    @property
    def poses(self): ...
    @property
    def duration(self): ...
    def draw_poses_background(self, color: Any): ...
    def draw_poses(self, image: Optional[Any] = ...): ...
    def draw_aliens(self): ...

class PoseEstimation(BaseService):
    def __init__(self, model_id: Any) -> None: ...
    def estimate(self, image: Any): ...
