# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['cntr', 'cntr.auth', 'cntr.b2b', 'cntr.core']

package_data = \
{'': ['*'],
 'cntr': ['email-templates/src/*',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.dockerignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/.gitignore',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/Dockerfile',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/README.md',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/babel.config.js',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/nginx-backend-not-found.conf',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package-lock.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/package.json',
          'static/frontend/public/*',
          'static/frontend/public/img/icons/*',
          'static/frontend/src/*',
          'static/frontend/src/assets/*',
          'static/frontend/src/components/*',
          'static/frontend/src/interfaces/*',
          'static/frontend/src/plugins/*',
          'static/frontend/src/store/*',
          'static/frontend/src/store/admin/*',
          'static/frontend/src/store/main/*',
          'static/frontend/src/views/*',
          'static/frontend/src/views/main/*',
          'static/frontend/src/views/main/admin/*',
          'static/frontend/src/views/main/profile/*',
          'static/frontend/tests/unit/*',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tsconfig.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/tslint.json',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js',
          'static/frontend/vue.config.js']}

install_requires = \
['Jinja2>=2.11.3,<3.0.0',
 'aiofiles>=0.6.0,<0.7.0',
 'alembic>=1.5.5,<2.0.0',
 'bcrypt>=3.2.0,<4.0.0',
 'celery>=5.0.5,<6.0.0',
 'email-validator>=1.1.2,<2.0.0',
 'emails>=0.6,<0.7',
 'fastapi>=0.63.0,<0.64.0',
 'httpx>=0.17.0,<0.18.0',
 'passlib>=1.7.4,<2.0.0',
 'pydantic[dotenv]>=1.8.1,<2.0.0',
 'pyodbc>=4.0.30,<5.0.0',
 'python-jose>=3.2.0,<4.0.0',
 'python-multipart>=0.0.5,<0.0.6',
 'raven>=6.10.0,<7.0.0',
 'tabulate>=0.8.9,<0.9.0',
 'uvicorn>=0.13.4,<0.14.0']

setup_kwargs = {
    'name': 'cntr',
    'version': '0.1.0',
    'description': 'ECommerce connector',
    'long_description': None,
    'author': 'Ming Shen',
    'author_email': None,
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.9,<4.0',
}


setup(**setup_kwargs)
