from typing import Any

LOGGER: Any
CREDENTIALS_DIR: Any
CREDENTIALS_PATH: Any
DEVICE_SYSTEM_ID_PATH: Any
DEV_HOST_SYSTEM_ID_PATH: Any
SYSTEM_ID_OPTIONS: Any
DEVICE: bool
DEVICE_MODE: Any
DEV_HOST: bool
USER_POOL_CONFIG: Any
REGION: str

def load_tokens_from_file(filepath: Any): ...
def load_system_id_from_file(filepath: Any): ...

class Token:
    token: Any = ...
    claims: Any = ...
    def __init__(self, token: Any, keys: Any) -> None: ...
    def decode(self): ...
    def validate_expiry(self): ...
    def get_audience(self, is_id_token: bool = ...): ...

def refresh_tokens(refresh_token: Any, user_pool_client_id: Any): ...

class TokenGroup:
    refresh_token: Any = ...
    id_token: Any = ...
    def __init__(self, token_file: Any, user_pool_id: Any, refresh_token: Any, undecoded_id_token: Any, keys: Any) -> None: ...
    def exists(self): ...
    def decode(self): ...
    def validate(self): ...
    def refresh(self, client_id: Any): ...

class DeviceTokens(TokenGroup):
    mode: Any = ...
    def __init__(self, token_file: Any) -> None: ...
    def exists(self): ...
    def decode(self): ...
    def refresh(self): ...

class DevelopmentHostTokens(TokenGroup):
    def __init__(self, token_file: Any) -> None: ...
    def exists(self): ...
    def refresh(self): ...

def validate_device_tokens(token_file: Any): ...
def validate_development_host_tokens(token_file: Any): ...
def validate_credentials() -> None: ...
