from edgeiq.constants import *
from edgeiq import edge_tools as edge_tools, runtime as runtime
from typing import Any

def get_opencv_engine(engine: Any): ...
def get_opencv_accelerator(accelerator: Any): ...

SUPPORTED_ACCELERATOR: Any
SUPPORTED_OPENCV_ENGINE: Any

def validate_engine_accelerator_pair(engine: Any, accelerator: Any, model_config: Any): ...

class BaseService:
    def __init__(self, model_config: Any) -> None: ...
    def load(self, engine: Any = ..., accelerator: Any = ...) -> None: ...
    @property
    def labels(self): ...
    @property
    def colors(self): ...
    @colors.setter
    def colors(self, colors: Any) -> None: ...
    @property
    def model_id(self): ...
    @property
    def engine(self): ...
    @property
    def accelerator(self): ...
    @property
    def model_purpose(self): ...
