import numpy as np
from typing import Any, Optional

class EyeCloudFrame(np.ndarray):
    def __new__(cls, frame: Any, sequence_index: Any): ...
    def __array_finalize__(self, frame_obj: Any) -> None: ...
    @property
    def sequence_index(self): ...

class EyeCloud:
    def __init__(self, model_id: Optional[Any] = ...) -> None: ...
    @property
    def model_id(self): ...
    @property
    def model_purpose(self): ...
    def start(self): ...
    def stop(self) -> None: ...
    def get_frame(self): ...
    def get_model_result(self, **inference_args: Any): ...
    def get_frame_data(self): ...
    def process_frame_data(self, frame_data: Any): ...
    def get_model_data(self): ...
    def __enter__(self): ...
    def __exit__(self, type: Any, value: Any, traceback: Any) -> None: ...
    def __del__(self) -> None: ...
