from edgeiq import constants as constants, edge_tools as edge_tools, processing as processing
from edgeiq.base_service import BaseService as BaseService
from typing import Any

class ClassificationPrediction:
    def __init__(self, confidence: Any, label: Any) -> None: ...
    @property
    def label(self): ...
    @property
    def confidence(self): ...

class ClassificationResults:
    def __init__(self, confidences: Any, labels: Any, start: Any, end: Any, image: Any): ...
    @property
    def duration(self): ...
    @property
    def predictions(self): ...
    @property
    def image(self): ...

class Classification(BaseService):
    def __init__(self, model_id: Any) -> None: ...
    def classify_image(self, image: Any, confidence_level: float = ...): ...
