import multiprocessing.queues
from edgeiq import edge_tools as edge_tools
from typing import Any

class _CircularQueue(multiprocessing.queues.Queue):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def put(self, obj: Any) -> None: ...

class MjpgVideoWriter:
    def __init__(self, queue_depth: int = ..., port: int = ..., max_image_width: int = ..., max_image_height: int = ..., jpg_quality: int = ..., **kwargs: Any) -> None: ...
    def start(self): ...
    def write_frame(self, frame: Any) -> None: ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: Any, value: Any, traceback: Any) -> None: ...
    def __del__(self) -> None: ...

def gen_video_feed() -> None: ...
def video(): ...

class _ServerProcess(multiprocessing.Process):
    def __init__(self, ipaddr: Any, port: Any, tx_queue: Any, max_image_width: Any, max_image_height: Any, jpg_quality: Any, error_queue: Any, *args: Any, **kwargs: Any) -> None: ...
    def run(self) -> None: ...
