from edgeiq import constants as constants, edge_tools as edge_tools, processing as processing
from edgeiq.base_service import BaseService as BaseService
from typing import Any

class SemanticSegmentationResults:
    def __init__(self, class_map: Any, start: Any, end: Any, image: Any) -> None: ...
    @property
    def duration(self): ...
    @property
    def class_map(self): ...
    @property
    def image(self): ...

class SemanticSegmentation(BaseService):
    def __init__(self, model_id: Any) -> None: ...
    def segment_image(self, image: Any): ...
    def build_image_mask(self, class_map: Any): ...
    def build_legend(self): ...
    def build_object_map(self, class_map: Any, class_list: Any): ...
