from __future__ import annotations

from typing import Tuple


class Vector2:
    x: float
    y: float

    def __init__(self, x: float = 0, y: float = 0): ...
    @classmethod
    def from_direction_magnitude(cls, angle: float, distance: float) -> Vector2: ...
    def as_tuple(self) -> Tuple[float, float]: ...
    def direction(self) -> float: ...
    def as_direction_magnitude(self) -> Tuple[float, float]: ...
    def sqr_magnitude(self) -> float: ...
    def magnitude(self) -> float: ...
    def set_to(self, x: float, y: float) -> None: ...
    def normalize(self) -> None: ...
    def copy(self) -> Vector2: ...
