# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: counter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='counter.proto',
  package='calixa.domain.counter',
  syntax='proto3',
  serialized_options=b'\n\021io.calixa.counterH\001P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcounter.proto\x12\x15\x63\x61lixa.domain.counter\x1a\x1fgoogle/protobuf/timestamp.proto\"{\n\nCounterKey\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x38\n\x0c\x63ounter_type\x18\x03 \x01(\x0e\x32\".calixa.domain.counter.CounterType\x12\r\n\x05param\x18\x04 \x01(\t\"\x94\x01\n\x12\x43ounterObservation\x12.\n\x03key\x18\x01 \x01(\x0b\x32!.calixa.domain.counter.CounterKey\x12/\n\x0bobserved_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\r\n\x05\x63ount\x18\x04 \x01(\x03\"c\n\x12\x43ounterValueAtTime\x12\x14\n\x0cvaluePresent\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x03\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*D\n\x0b\x43ounterType\x12\x1c\n\x18\x43OUNTER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13\x43OUNTER_TYPE_METRIC\x10\x01*\x82\x01\n\x07GroupBy\x12\x18\n\x14GROUP_BY_UNSPECIFIED\x10\x00\x12\x11\n\rGROUP_BY_HOUR\x10\x01\x12\x10\n\x0cGROUP_BY_DAY\x10\x02\x12\x11\n\rGROUP_BY_WEEK\x10\x03\x12\x12\n\x0eGROUP_BY_MONTH\x10\x04\x12\x11\n\rGROUP_BY_YEAR\x10\x05*\x92\x01\n\x12\x41ggregateOperation\x12#\n\x1f\x41GGREGATE_OPERATION_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x41GGREGATE_OPERATION_SUM\x10\x01\x12\x1b\n\x17\x41GGREGATE_OPERATION_AVG\x10\x02\x12\x1d\n\x19\x41GGREGATE_OPERATION_COUNT\x10\x03\x42\x17\n\x11io.calixa.counterH\x01P\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_COUNTERTYPE = _descriptor.EnumDescriptor(
  name='CounterType',
  full_name='calixa.domain.counter.CounterType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COUNTER_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNTER_TYPE_METRIC', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=450,
  serialized_end=518,
)
_sym_db.RegisterEnumDescriptor(_COUNTERTYPE)

CounterType = enum_type_wrapper.EnumTypeWrapper(_COUNTERTYPE)
_GROUPBY = _descriptor.EnumDescriptor(
  name='GroupBy',
  full_name='calixa.domain.counter.GroupBy',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GROUP_BY_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GROUP_BY_HOUR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GROUP_BY_DAY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GROUP_BY_WEEK', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GROUP_BY_MONTH', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GROUP_BY_YEAR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=521,
  serialized_end=651,
)
_sym_db.RegisterEnumDescriptor(_GROUPBY)

GroupBy = enum_type_wrapper.EnumTypeWrapper(_GROUPBY)
_AGGREGATEOPERATION = _descriptor.EnumDescriptor(
  name='AggregateOperation',
  full_name='calixa.domain.counter.AggregateOperation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AGGREGATE_OPERATION_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AGGREGATE_OPERATION_SUM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AGGREGATE_OPERATION_AVG', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AGGREGATE_OPERATION_COUNT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=654,
  serialized_end=800,
)
_sym_db.RegisterEnumDescriptor(_AGGREGATEOPERATION)

AggregateOperation = enum_type_wrapper.EnumTypeWrapper(_AGGREGATEOPERATION)
COUNTER_TYPE_UNSPECIFIED = 0
COUNTER_TYPE_METRIC = 1
GROUP_BY_UNSPECIFIED = 0
GROUP_BY_HOUR = 1
GROUP_BY_DAY = 2
GROUP_BY_WEEK = 3
GROUP_BY_MONTH = 4
GROUP_BY_YEAR = 5
AGGREGATE_OPERATION_UNSPECIFIED = 0
AGGREGATE_OPERATION_SUM = 1
AGGREGATE_OPERATION_AVG = 2
AGGREGATE_OPERATION_COUNT = 3



_COUNTERKEY = _descriptor.Descriptor(
  name='CounterKey',
  full_name='calixa.domain.counter.CounterKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='organization_id', full_name='calixa.domain.counter.CounterKey.organization_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='calixa.domain.counter.CounterKey.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter_type', full_name='calixa.domain.counter.CounterKey.counter_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param', full_name='calixa.domain.counter.CounterKey.param', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=196,
)


_COUNTEROBSERVATION = _descriptor.Descriptor(
  name='CounterObservation',
  full_name='calixa.domain.counter.CounterObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='calixa.domain.counter.CounterObservation.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='observed_at', full_name='calixa.domain.counter.CounterObservation.observed_at', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='calixa.domain.counter.CounterObservation.amount', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='calixa.domain.counter.CounterObservation.count', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=347,
)


_COUNTERVALUEATTIME = _descriptor.Descriptor(
  name='CounterValueAtTime',
  full_name='calixa.domain.counter.CounterValueAtTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valuePresent', full_name='calixa.domain.counter.CounterValueAtTime.valuePresent', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='calixa.domain.counter.CounterValueAtTime.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='calixa.domain.counter.CounterValueAtTime.time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=448,
)

_COUNTERKEY.fields_by_name['counter_type'].enum_type = _COUNTERTYPE
_COUNTEROBSERVATION.fields_by_name['key'].message_type = _COUNTERKEY
_COUNTEROBSERVATION.fields_by_name['observed_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_COUNTERVALUEATTIME.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['CounterKey'] = _COUNTERKEY
DESCRIPTOR.message_types_by_name['CounterObservation'] = _COUNTEROBSERVATION
DESCRIPTOR.message_types_by_name['CounterValueAtTime'] = _COUNTERVALUEATTIME
DESCRIPTOR.enum_types_by_name['CounterType'] = _COUNTERTYPE
DESCRIPTOR.enum_types_by_name['GroupBy'] = _GROUPBY
DESCRIPTOR.enum_types_by_name['AggregateOperation'] = _AGGREGATEOPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CounterKey = _reflection.GeneratedProtocolMessageType('CounterKey', (_message.Message,), {
  'DESCRIPTOR' : _COUNTERKEY,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.counter.CounterKey)
  })
_sym_db.RegisterMessage(CounterKey)

CounterObservation = _reflection.GeneratedProtocolMessageType('CounterObservation', (_message.Message,), {
  'DESCRIPTOR' : _COUNTEROBSERVATION,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.counter.CounterObservation)
  })
_sym_db.RegisterMessage(CounterObservation)

CounterValueAtTime = _reflection.GeneratedProtocolMessageType('CounterValueAtTime', (_message.Message,), {
  'DESCRIPTOR' : _COUNTERVALUEATTIME,
  '__module__' : 'counter_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.counter.CounterValueAtTime)
  })
_sym_db.RegisterMessage(CounterValueAtTime)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
