# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iMATURE.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1179, 950)
        MainWindow.setMaximumSize(QtCore.QSize(2281, 1200))
        icon = QtGui.QIcon()
        iconDir = os.path.dirname(os.path.abspath(__file__))
        icon.addPixmap(QtGui.QPixmap(iconDir + os.path.sep + 'iMATURE_icon.ico'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #icon.addPixmap(QtGui.QPixmap("iMATURE_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frameOutput1 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameOutput1.sizePolicy().hasHeightForWidth())
        self.frameOutput1.setSizePolicy(sizePolicy)
        self.frameOutput1.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frameOutput1.setAutoFillBackground(False)
        self.frameOutput1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameOutput1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOutput1.setObjectName("frameOutput1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameOutput1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frameOutput1)
        self.label_2.setMaximumSize(QtCore.QSize(800, 50))
        self.label_2.setText("")
        logoDir = os.path.dirname(os.path.abspath(__file__))
        self.label_2.setPixmap(QtGui.QPixmap(logoDir + os.path.sep +'iMATURE_highres2.png'))
        #self.label_2.setPixmap(QtGui.QPixmap("iMATURE_highres2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lblModel1 = QtWidgets.QLabel(self.frameOutput1)
        self.lblModel1.setObjectName("lblModel1")
        self.verticalLayout.addWidget(self.lblModel1)
        self.cmbModel1 = QtWidgets.QComboBox(self.frameOutput1)
        self.cmbModel1.setMaximumSize(QtCore.QSize(800, 16777215))
        self.cmbModel1.setObjectName("cmbModel1")
        self.verticalLayout.addWidget(self.cmbModel1)
        self.s1s2plot_ref1 = QtWidgets.QTabWidget(self.frameOutput1)
        self.s1s2plot_ref1.setMaximumSize(QtCore.QSize(800, 16777215))
        self.s1s2plot_ref1.setObjectName("s1s2plot_ref1")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(self.tab)
        self.tabWidget.setMaximumSize(QtCore.QSize(900, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblAPDCaTModel1Ctrl = QtWidgets.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.lblAPDCaTModel1Ctrl.setFont(font)
        self.lblAPDCaTModel1Ctrl.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAPDCaTModel1Ctrl.setObjectName("lblAPDCaTModel1Ctrl")
        self.gridLayout_7.addWidget(self.lblAPDCaTModel1Ctrl, 0, 0, 1, 1)
        self.lblAPDCaTModel1Alt = QtWidgets.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.lblAPDCaTModel1Alt.setFont(font)
        self.lblAPDCaTModel1Alt.setStyleSheet("color:red;")
        self.lblAPDCaTModel1Alt.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAPDCaTModel1Alt.setObjectName("lblAPDCaTModel1Alt")
        self.gridLayout_7.addWidget(self.lblAPDCaTModel1Alt, 1, 0, 1, 1)
        self.lblAPDCaTModel1Alt_2 = QtWidgets.QLabel(self.tabWidgetPage1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.lblAPDCaTModel1Alt_2.setFont(font)
        self.lblAPDCaTModel1Alt_2.setStyleSheet("color:blue;")
        self.lblAPDCaTModel1Alt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAPDCaTModel1Alt_2.setObjectName("lblAPDCaTModel1Alt_2")
        self.gridLayout_7.addWidget(self.lblAPDCaTModel1Alt_2, 2, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.gridLayout_12.addWidget(self.tabWidget, 4, 0, 1, 9)
        self.cmbOutput1Top = QtWidgets.QComboBox(self.tab)
        self.cmbOutput1Top.setMinimumSize(QtCore.QSize(450, 0))
        self.cmbOutput1Top.setObjectName("cmbOutput1Top")
        self.gridLayout_12.addWidget(self.cmbOutput1Top, 0, 0, 1, 1)
        self.cmbOutput1Bottom = QtWidgets.QComboBox(self.tab)
        self.cmbOutput1Bottom.setMinimumSize(QtCore.QSize(450, 0))
        self.cmbOutput1Bottom.setObjectName("cmbOutput1Bottom")
        self.gridLayout_12.addWidget(self.cmbOutput1Bottom, 2, 0, 1, 1)
        self.mplOutput1Top = MatplotlibWidget5.MatplotlibWidget(self.tab)
        self.mplOutput1Top.setMaximumSize(QtCore.QSize(800, 16777215))
        self.mplOutput1Top.setObjectName("mplOutput1Top")
        self.gridLayout_12.addWidget(self.mplOutput1Top, 1, 0, 1, 8)
        self.mplOutput1Bottom = MatplotlibWidget5.MatplotlibWidget(self.tab)
        self.mplOutput1Bottom.setMaximumSize(QtCore.QSize(800, 16777215))
        self.mplOutput1Bottom.setObjectName("mplOutput1Bottom")
        self.gridLayout_12.addWidget(self.mplOutput1Bottom, 3, 0, 1, 8)
        self.aad2_mdl1_top = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.aad2_mdl1_top.setFont(font)
        self.aad2_mdl1_top.setStyleSheet("color:blue;")
        self.aad2_mdl1_top.setObjectName("aad2_mdl1_top")
        self.gridLayout_12.addWidget(self.aad2_mdl1_top, 0, 7, 1, 1)
        self.aad1_mdl1_top = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.aad1_mdl1_top.setFont(font)
        self.aad1_mdl1_top.setStyleSheet("color:red;")
        self.aad1_mdl1_top.setObjectName("aad1_mdl1_top")
        self.gridLayout_12.addWidget(self.aad1_mdl1_top, 0, 6, 1, 1)
        self.ref_mdl1_top = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ref_mdl1_top.setFont(font)
        self.ref_mdl1_top.setObjectName("ref_mdl1_top")
        self.gridLayout_12.addWidget(self.ref_mdl1_top, 0, 5, 1, 1)
        self.aad2_mdl1_bottom = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.aad2_mdl1_bottom.setFont(font)
        self.aad2_mdl1_bottom.setStyleSheet("color:blue;")
        self.aad2_mdl1_bottom.setObjectName("aad2_mdl1_bottom")
        self.gridLayout_12.addWidget(self.aad2_mdl1_bottom, 2, 7, 1, 1)
        self.aad1_mdl1_bottom = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.aad1_mdl1_bottom.setFont(font)
        self.aad1_mdl1_bottom.setStyleSheet("color:red;")
        self.aad1_mdl1_bottom.setObjectName("aad1_mdl1_bottom")
        self.gridLayout_12.addWidget(self.aad1_mdl1_bottom, 2, 6, 1, 1)
        self.ref_mdl1_bottom = QtWidgets.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ref_mdl1_bottom.setFont(font)
        self.ref_mdl1_bottom.setObjectName("ref_mdl1_bottom")
        self.gridLayout_12.addWidget(self.ref_mdl1_bottom, 2, 5, 1, 1)
        self.s1s2plot_ref1.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 18, 1, 1, 1)
        self.spinShowbeatsModel1 = QtWidgets.QSpinBox(self.tab_2)
        self.spinShowbeatsModel1.setMinimum(1)
        self.spinShowbeatsModel1.setMaximum(1000)
        self.spinShowbeatsModel1.setProperty("value", 3)
        self.spinShowbeatsModel1.setObjectName("spinShowbeatsModel1")
        self.gridLayout_4.addWidget(self.spinShowbeatsModel1, 8, 3, 2, 1)
        self.spinStimAmp1 = QtWidgets.QSpinBox(self.tab_2)
        self.spinStimAmp1.setMaximum(1000)
        self.spinStimAmp1.setSingleStep(10)
        self.spinStimAmp1.setProperty("value", 50)
        self.spinStimAmp1.setObjectName("spinStimAmp1")
        self.gridLayout_4.addWidget(self.spinStimAmp1, 4, 3, 1, 1)
        self.spinStimDur1 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.spinStimDur1.setDecimals(1)
        self.spinStimDur1.setMaximum(1000.0)
        self.spinStimDur1.setProperty("value", 1.0)
        self.spinStimDur1.setObjectName("spinStimDur1")
        self.gridLayout_4.addWidget(self.spinStimDur1, 3, 3, 1, 1)
        self.lblPrepacing1 = QtWidgets.QLabel(self.tab_2)
        self.lblPrepacing1.setObjectName("lblPrepacing1")
        self.gridLayout_4.addWidget(self.lblPrepacing1, 7, 1, 1, 1)
        self.spinPrepacingModel1 = QtWidgets.QSpinBox(self.tab_2)
        self.spinPrepacingModel1.setMaximum(1000)
        self.spinPrepacingModel1.setSingleStep(10)
        self.spinPrepacingModel1.setProperty("value", 100)
        self.spinPrepacingModel1.setObjectName("spinPrepacingModel1")
        self.gridLayout_4.addWidget(self.spinPrepacingModel1, 7, 3, 1, 1)
        self.lblStimDur1 = QtWidgets.QLabel(self.tab_2)
        self.lblStimDur1.setObjectName("lblStimDur1")
        self.gridLayout_4.addWidget(self.lblStimDur1, 3, 1, 1, 1)
        self.lblRate = QtWidgets.QLabel(self.tab_2)
        self.lblRate.setObjectName("lblRate")
        self.gridLayout_4.addWidget(self.lblRate, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 10, 2, 1, 1)
        self.spinKo1 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.spinKo1.setSingleStep(0.1)
        self.spinKo1.setProperty("value", 4.0)
        self.spinKo1.setObjectName("spinKo1")
        self.gridLayout_4.addWidget(self.spinKo1, 13, 3, 1, 1)
        self.lblShowbeats1 = QtWidgets.QLabel(self.tab_2)
        self.lblShowbeats1.setObjectName("lblShowbeats1")
        self.gridLayout_4.addWidget(self.lblShowbeats1, 8, 1, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 5, 1, 1, 1)
        self.lblNao1 = QtWidgets.QLabel(self.tab_2)
        self.lblNao1.setObjectName("lblNao1")
        self.gridLayout_4.addWidget(self.lblNao1, 14, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 20, 1, 1, 1)
        self.lblStimAmp1 = QtWidgets.QLabel(self.tab_2)
        self.lblStimAmp1.setObjectName("lblStimAmp1")
        self.gridLayout_4.addWidget(self.lblStimAmp1, 4, 1, 1, 1)
        self.stimamp = QtWidgets.QSpinBox(self.tab_2)
        self.stimamp.setMinimum(-200)
        self.stimamp.setMaximum(-40)
        self.stimamp.setSingleStep(10)
        self.stimamp.setProperty("value", -120)
        self.stimamp.setObjectName("stimamp")
        self.gridLayout_4.addWidget(self.stimamp, 5, 3, 1, 1)
        self.txtRateModel1 = QtWidgets.QLineEdit(self.tab_2)
        self.txtRateModel1.setObjectName("txtRateModel1")
        self.gridLayout_4.addWidget(self.txtRateModel1, 1, 3, 1, 1)
        self.spinNao1 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.spinNao1.setMaximum(300.0)
        self.spinNao1.setProperty("value", 140.0)
        self.spinNao1.setObjectName("spinNao1")
        self.gridLayout_4.addWidget(self.spinNao1, 14, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 16, 1, 1, 1)
        self.lblCao1 = QtWidgets.QLabel(self.tab_2)
        self.lblCao1.setObjectName("lblCao1")
        self.gridLayout_4.addWidget(self.lblCao1, 12, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 17, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 19, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 15, 1, 1, 1)
        self.lblSettingsExtracellular1 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSettingsExtracellular1.setFont(font)
        self.lblSettingsExtracellular1.setObjectName("lblSettingsExtracellular1")
        self.gridLayout_4.addWidget(self.lblSettingsExtracellular1, 11, 1, 1, 1)
        self.lblKo1 = QtWidgets.QLabel(self.tab_2)
        self.lblKo1.setObjectName("lblKo1")
        self.gridLayout_4.addWidget(self.lblKo1, 13, 1, 1, 1)
        self.lblSettingsStimulus1 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSettingsStimulus1.setFont(font)
        self.lblSettingsStimulus1.setObjectName("lblSettingsStimulus1")
        self.gridLayout_4.addWidget(self.lblSettingsStimulus1, 0, 1, 1, 1)
        self.spinCao1 = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.spinCao1.setMaximum(20.0)
        self.spinCao1.setSingleStep(0.1)
        self.spinCao1.setProperty("value", 2.0)
        self.spinCao1.setObjectName("spinCao1")
        self.gridLayout_4.addWidget(self.spinCao1, 12, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 6, 1, 1, 1)
        self.I_hyper = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.I_hyper.setDecimals(1)
        self.I_hyper.setMinimum(0.0)
        self.I_hyper.setMaximum(5.0)
        self.I_hyper.setSingleStep(0.1)
        self.I_hyper.setObjectName("I_hyper")
        self.gridLayout_4.addWidget(self.I_hyper, 6, 3, 1, 1)
        self.s1s2plot_ref1.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.export_1 = QtWidgets.QPushButton(self.tab_7)
        self.export_1.setObjectName("export_1")
        self.verticalLayout_12.addWidget(self.export_1)
        self.label_13 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.label_26 = QtWidgets.QLabel(self.tab_7)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_12.addWidget(self.label_26)
        spacerItem7 = QtWidgets.QSpacerItem(20, 125, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem7)
        self.label_9 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(True)
        self.label_9.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.s1s2plot_ref1.addTab(self.tab_7, "")
        self.verticalLayout.addWidget(self.s1s2plot_ref1)
        self.gridLayout_3.addWidget(self.frameOutput1, 0, 1, 1, 1)
        self.frameControls = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameControls.sizePolicy().hasHeightForWidth())
        self.frameControls.setSizePolicy(sizePolicy)
        self.frameControls.setMinimumSize(QtCore.QSize(350, 0))
        self.frameControls.setAutoFillBackground(False)
        self.frameControls.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameControls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameControls.setObjectName("frameControls")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameControls)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabGeneral = QtWidgets.QTabWidget(self.frameControls)
        self.tabGeneral.setObjectName("tabGeneral")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.slideINaK = QtWidgets.QSlider(self.tab_5)
        self.slideINaK.setMinimum(-200)
        self.slideINaK.setMaximum(100)
        self.slideINaK.setSingleStep(5)
        self.slideINaK.setPageStep(20)
        self.slideINaK.setOrientation(QtCore.Qt.Horizontal)
        self.slideINaK.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideINaK.setTickInterval(25)
        self.slideINaK.setObjectName("slideINaK")
        self.gridLayout.addWidget(self.slideINaK, 9, 1, 1, 1)
        self.label100Percent_9 = QtWidgets.QLabel(self.tab_5)
        self.label100Percent_9.setObjectName("label100Percent_9")
        self.gridLayout.addWidget(self.label100Percent_9, 11, 2, 1, 1)
        self.spinIK1 = QtWidgets.QSpinBox(self.tab_5)
        self.spinIK1.setMinimum(-200)
        self.spinIK1.setMaximum(100)
        self.spinIK1.setSingleStep(5)
        self.spinIK1.setObjectName("spinIK1")
        self.gridLayout.addWidget(self.spinIK1, 1, 3, 1, 1)
        self.label100Percent_7 = QtWidgets.QLabel(self.tab_5)
        self.label100Percent_7.setObjectName("label100Percent_7")
        self.gridLayout.addWidget(self.label100Percent_7, 10, 2, 1, 1)
        self.lblINaK = QtWidgets.QLabel(self.tab_5)
        self.lblINaK.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblINaK.setObjectName("lblINaK")
        self.gridLayout.addWidget(self.lblINaK, 9, 0, 1, 1)
        self.slideIto = QtWidgets.QSlider(self.tab_5)
        self.slideIto.setMinimum(-200)
        self.slideIto.setMaximum(100)
        self.slideIto.setSingleStep(5)
        self.slideIto.setPageStep(20)
        self.slideIto.setOrientation(QtCore.Qt.Horizontal)
        self.slideIto.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIto.setTickInterval(25)
        self.slideIto.setObjectName("slideIto")
        self.gridLayout.addWidget(self.slideIto, 11, 1, 1, 1)
        self.spinIto = QtWidgets.QSpinBox(self.tab_5)
        self.spinIto.setMinimum(-200)
        self.spinIto.setMaximum(100)
        self.spinIto.setSingleStep(5)
        self.spinIto.setObjectName("spinIto")
        self.gridLayout.addWidget(self.spinIto, 11, 3, 1, 1)
        self.label100Percent = QtWidgets.QLabel(self.tab_5)
        self.label100Percent.setObjectName("label100Percent")
        self.gridLayout.addWidget(self.label100Percent, 6, 2, 1, 1)
        self.lblINCX = QtWidgets.QLabel(self.tab_5)
        self.lblINCX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblINCX.setObjectName("lblINCX")
        self.gridLayout.addWidget(self.lblINCX, 10, 0, 1, 1)
        self.lblINa = QtWidgets.QLabel(self.tab_5)
        self.lblINa.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblINa.setObjectName("lblINa")
        self.gridLayout.addWidget(self.lblINa, 6, 0, 1, 1)
        self.lblIto = QtWidgets.QLabel(self.tab_5)
        self.lblIto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIto.setObjectName("lblIto")
        self.gridLayout.addWidget(self.lblIto, 11, 0, 1, 1)
        self.slideINCX = QtWidgets.QSlider(self.tab_5)
        self.slideINCX.setMinimum(-200)
        self.slideINCX.setMaximum(100)
        self.slideINCX.setSingleStep(5)
        self.slideINCX.setPageStep(20)
        self.slideINCX.setOrientation(QtCore.Qt.Horizontal)
        self.slideINCX.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideINCX.setTickInterval(25)
        self.slideINCX.setObjectName("slideINCX")
        self.gridLayout.addWidget(self.slideINCX, 10, 1, 1, 1)
        self.label100Percent_6 = QtWidgets.QLabel(self.tab_5)
        self.label100Percent_6.setObjectName("label100Percent_6")
        self.gridLayout.addWidget(self.label100Percent_6, 9, 2, 1, 1)
        self.label100Percent_10 = QtWidgets.QLabel(self.tab_5)
        self.label100Percent_10.setObjectName("label100Percent_10")
        self.gridLayout.addWidget(self.label100Percent_10, 7, 2, 1, 1)
        self.spinINCX = QtWidgets.QSpinBox(self.tab_5)
        self.spinINCX.setMinimum(-200)
        self.spinINCX.setMaximum(100)
        self.spinINCX.setSingleStep(5)
        self.spinINCX.setObjectName("spinINCX")
        self.gridLayout.addWidget(self.spinINCX, 10, 3, 1, 1)
        self.spinIKs = QtWidgets.QSpinBox(self.tab_5)
        self.spinIKs.setMinimum(-200)
        self.spinIKs.setMaximum(100)
        self.spinIKs.setSingleStep(5)
        self.spinIKs.setObjectName("spinIKs")
        self.gridLayout.addWidget(self.spinIKs, 3, 3, 1, 1)
        self.lblIKs = QtWidgets.QLabel(self.tab_5)
        self.lblIKs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIKs.setObjectName("lblIKs")
        self.gridLayout.addWidget(self.lblIKs, 3, 0, 1, 1)
        self.slideINa = QtWidgets.QSlider(self.tab_5)
        self.slideINa.setMinimum(-200)
        self.slideINa.setMaximum(100)
        self.slideINa.setSingleStep(5)
        self.slideINa.setPageStep(20)
        self.slideINa.setOrientation(QtCore.Qt.Horizontal)
        self.slideINa.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideINa.setTickInterval(25)
        self.slideINa.setObjectName("slideINa")
        self.gridLayout.addWidget(self.slideINa, 6, 1, 1, 1)
        self.lblINaL = QtWidgets.QLabel(self.tab_5)
        self.lblINaL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblINaL.setObjectName("lblINaL")
        self.gridLayout.addWidget(self.lblINaL, 7, 0, 1, 1)
        self.slideIK1 = QtWidgets.QSlider(self.tab_5)
        self.slideIK1.setMinimum(-200)
        self.slideIK1.setMaximum(100)
        self.slideIK1.setSingleStep(5)
        self.slideIK1.setPageStep(20)
        self.slideIK1.setOrientation(QtCore.Qt.Horizontal)
        self.slideIK1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIK1.setTickInterval(25)
        self.slideIK1.setObjectName("slideIK1")
        self.gridLayout.addWidget(self.slideIK1, 1, 1, 1, 1)
        self.label100Percent_5 = QtWidgets.QLabel(self.tab_5)
        self.label100Percent_5.setObjectName("label100Percent_5")
        self.gridLayout.addWidget(self.label100Percent_5, 0, 2, 1, 1)
        self.lblIK1 = QtWidgets.QLabel(self.tab_5)
        self.lblIK1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblIK1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIK1.setObjectName("lblIK1")
        self.gridLayout.addWidget(self.lblIK1, 1, 0, 1, 1)
        self.spinINaK = QtWidgets.QSpinBox(self.tab_5)
        self.spinINaK.setMinimum(-200)
        self.spinINaK.setMaximum(100)
        self.spinINaK.setSingleStep(5)
        self.spinINaK.setObjectName("spinINaK")
        self.gridLayout.addWidget(self.spinINaK, 9, 3, 1, 1)
        self.spinIKr = QtWidgets.QSpinBox(self.tab_5)
        self.spinIKr.setMinimum(-200)
        self.spinIKr.setMaximum(100)
        self.spinIKr.setSingleStep(5)
        self.spinIKr.setObjectName("spinIKr")
        self.gridLayout.addWidget(self.spinIKr, 2, 3, 1, 1)
        self.slideICaL = QtWidgets.QSlider(self.tab_5)
        self.slideICaL.setMinimum(-200)
        self.slideICaL.setMaximum(100)
        self.slideICaL.setSingleStep(5)
        self.slideICaL.setPageStep(20)
        self.slideICaL.setOrientation(QtCore.Qt.Horizontal)
        self.slideICaL.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideICaL.setTickInterval(25)
        self.slideICaL.setObjectName("slideICaL")
        self.gridLayout.addWidget(self.slideICaL, 0, 1, 1, 1)
        self.label100Percent_2 = QtWidgets.QLabel(self.tab_5)
        self.label100Percent_2.setObjectName("label100Percent_2")
        self.gridLayout.addWidget(self.label100Percent_2, 2, 2, 1, 1)
        self.spinINa = QtWidgets.QSpinBox(self.tab_5)
        self.spinINa.setMinimum(-200)
        self.spinINa.setMaximum(100)
        self.spinINa.setSingleStep(5)
        self.spinINa.setObjectName("spinINa")
        self.gridLayout.addWidget(self.spinINa, 6, 3, 1, 1)
        self.lblICaL = QtWidgets.QLabel(self.tab_5)
        self.lblICaL.setIndent(2)
        self.lblICaL.setObjectName("lblICaL")
        self.gridLayout.addWidget(self.lblICaL, 0, 0, 1, 1)
        self.spinICaL = QtWidgets.QSpinBox(self.tab_5)
        self.spinICaL.setMinimum(-200)
        self.spinICaL.setMaximum(100)
        self.spinICaL.setSingleStep(5)
        self.spinICaL.setObjectName("spinICaL")
        self.gridLayout.addWidget(self.spinICaL, 0, 3, 1, 1)
        self.slideIKs = QtWidgets.QSlider(self.tab_5)
        self.slideIKs.setMinimum(-200)
        self.slideIKs.setMaximum(100)
        self.slideIKs.setSingleStep(5)
        self.slideIKs.setPageStep(20)
        self.slideIKs.setOrientation(QtCore.Qt.Horizontal)
        self.slideIKs.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIKs.setTickInterval(25)
        self.slideIKs.setObjectName("slideIKs")
        self.gridLayout.addWidget(self.slideIKs, 3, 1, 1, 1)
        self.slideINaL = QtWidgets.QSlider(self.tab_5)
        self.slideINaL.setMinimum(-200)
        self.slideINaL.setMaximum(100)
        self.slideINaL.setSingleStep(5)
        self.slideINaL.setPageStep(20)
        self.slideINaL.setOrientation(QtCore.Qt.Horizontal)
        self.slideINaL.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideINaL.setTickInterval(25)
        self.slideINaL.setObjectName("slideINaL")
        self.gridLayout.addWidget(self.slideINaL, 7, 1, 1, 1)
        self.spinINaL = QtWidgets.QSpinBox(self.tab_5)
        self.spinINaL.setMinimum(-200)
        self.spinINaL.setMaximum(100)
        self.spinINaL.setSingleStep(5)
        self.spinINaL.setObjectName("spinINaL")
        self.gridLayout.addWidget(self.spinINaL, 7, 3, 1, 1)
        self.label100Percent_3 = QtWidgets.QLabel(self.tab_5)
        self.label100Percent_3.setObjectName("label100Percent_3")
        self.gridLayout.addWidget(self.label100Percent_3, 3, 2, 1, 1)
        self.label100Percent_4 = QtWidgets.QLabel(self.tab_5)
        self.label100Percent_4.setObjectName("label100Percent_4")
        self.gridLayout.addWidget(self.label100Percent_4, 1, 2, 1, 1)
        self.slideIKr = QtWidgets.QSlider(self.tab_5)
        self.slideIKr.setMinimum(-200)
        self.slideIKr.setMaximum(100)
        self.slideIKr.setSingleStep(5)
        self.slideIKr.setPageStep(20)
        self.slideIKr.setOrientation(QtCore.Qt.Horizontal)
        self.slideIKr.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIKr.setTickInterval(25)
        self.slideIKr.setObjectName("slideIKr")
        self.gridLayout.addWidget(self.slideIKr, 2, 1, 1, 1)
        self.lblIKr = QtWidgets.QLabel(self.tab_5)
        self.lblIKr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIKr.setObjectName("lblIKr")
        self.gridLayout.addWidget(self.lblIKr, 2, 0, 1, 1)
        self.slideIf = QtWidgets.QSlider(self.tab_5)
        self.slideIf.setMinimum(-200)
        self.slideIf.setMaximum(100)
        self.slideIf.setSingleStep(5)
        self.slideIf.setPageStep(20)
        self.slideIf.setOrientation(QtCore.Qt.Horizontal)
        self.slideIf.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIf.setTickInterval(25)
        self.slideIf.setObjectName("slideIf")
        self.gridLayout.addWidget(self.slideIf, 4, 1, 1, 1)
        self.lblIKur = QtWidgets.QLabel(self.tab_5)
        self.lblIKur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIKur.setObjectName("lblIKur")
        self.gridLayout.addWidget(self.lblIKur, 4, 0, 1, 1)
        self.spinIf = QtWidgets.QSpinBox(self.tab_5)
        self.spinIf.setMinimum(-200)
        self.spinIf.setMaximum(100)
        self.spinIf.setSingleStep(5)
        self.spinIf.setObjectName("spinIf")
        self.gridLayout.addWidget(self.spinIf, 4, 3, 1, 1)
        self.label100Percent_8 = QtWidgets.QLabel(self.tab_5)
        self.label100Percent_8.setObjectName("label100Percent_8")
        self.gridLayout.addWidget(self.label100Percent_8, 4, 2, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout, 4, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem8, 5, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_16.addItem(spacerItem9, 2, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_16.addWidget(self.label_24, 3, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblConcentration = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblConcentration.setFont(font)
        self.lblConcentration.setObjectName("lblConcentration")
        self.gridLayout_2.addWidget(self.lblConcentration, 0, 1, 1, 1)
        self.spinAADConcentration = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.spinAADConcentration.setDecimals(0)
        self.spinAADConcentration.setMinimum(20.0)
        self.spinAADConcentration.setMaximum(80.0)
        self.spinAADConcentration.setSingleStep(1.0)
        self.spinAADConcentration.setProperty("value", 30.0)
        self.spinAADConcentration.setObjectName("spinAADConcentration")
        self.gridLayout_2.addWidget(self.spinAADConcentration, 0, 2, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_16.addWidget(self.label_6, 1, 0, 1, 1)
        self.tabGeneral.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_17.addItem(spacerItem10, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_17.addWidget(self.label_25, 3, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.spinAADConcentration_3 = QtWidgets.QDoubleSpinBox(self.tab_9)
        self.spinAADConcentration_3.setDecimals(0)
        self.spinAADConcentration_3.setMinimum(20.0)
        self.spinAADConcentration_3.setMaximum(80.0)
        self.spinAADConcentration_3.setSingleStep(1.0)
        self.spinAADConcentration_3.setProperty("value", 30.0)
        self.spinAADConcentration_3.setObjectName("spinAADConcentration_3")
        self.gridLayout_6.addWidget(self.spinAADConcentration_3, 0, 2, 1, 1)
        self.lblConcentration_3 = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblConcentration_3.setFont(font)
        self.lblConcentration_3.setObjectName("lblConcentration_3")
        self.gridLayout_6.addWidget(self.lblConcentration_3, 0, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_6, 0, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem11, 5, 0, 1, 2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.slideIf_2 = QtWidgets.QSlider(self.tab_9)
        self.slideIf_2.setMinimum(-200)
        self.slideIf_2.setMaximum(100)
        self.slideIf_2.setSingleStep(5)
        self.slideIf_2.setPageStep(20)
        self.slideIf_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideIf_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIf_2.setTickInterval(25)
        self.slideIf_2.setObjectName("slideIf_2")
        self.gridLayout_5.addWidget(self.slideIf_2, 4, 1, 1, 1)
        self.spinINaK_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinINaK_2.setMinimum(-200)
        self.spinINaK_2.setMaximum(100)
        self.spinINaK_2.setSingleStep(5)
        self.spinINaK_2.setObjectName("spinINaK_2")
        self.gridLayout_5.addWidget(self.spinINaK_2, 7, 3, 1, 1)
        self.lblINa_2 = QtWidgets.QLabel(self.tab_9)
        self.lblINa_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblINa_2.setObjectName("lblINa_2")
        self.gridLayout_5.addWidget(self.lblINa_2, 5, 0, 1, 1)
        self.lblINCX_2 = QtWidgets.QLabel(self.tab_9)
        self.lblINCX_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblINCX_2.setObjectName("lblINCX_2")
        self.gridLayout_5.addWidget(self.lblINCX_2, 8, 0, 1, 1)
        self.spinINa_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinINa_2.setMinimum(-200)
        self.spinINa_2.setMaximum(100)
        self.spinINa_2.setSingleStep(5)
        self.spinINa_2.setObjectName("spinINa_2")
        self.gridLayout_5.addWidget(self.spinINa_2, 5, 3, 1, 1)
        self.label100Percent_15 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_15.setObjectName("label100Percent_15")
        self.gridLayout_5.addWidget(self.label100Percent_15, 4, 2, 1, 1)
        self.label100Percent_20 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_20.setObjectName("label100Percent_20")
        self.gridLayout_5.addWidget(self.label100Percent_20, 8, 2, 1, 1)
        self.slideINa_2 = QtWidgets.QSlider(self.tab_9)
        self.slideINa_2.setMinimum(-200)
        self.slideINa_2.setMaximum(100)
        self.slideINa_2.setSingleStep(5)
        self.slideINa_2.setPageStep(20)
        self.slideINa_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideINa_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideINa_2.setTickInterval(25)
        self.slideINa_2.setObjectName("slideINa_2")
        self.gridLayout_5.addWidget(self.slideINa_2, 5, 1, 1, 1)
        self.lblINaK_2 = QtWidgets.QLabel(self.tab_9)
        self.lblINaK_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblINaK_2.setObjectName("lblINaK_2")
        self.gridLayout_5.addWidget(self.lblINaK_2, 7, 0, 1, 1)
        self.label100Percent_19 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_19.setObjectName("label100Percent_19")
        self.gridLayout_5.addWidget(self.label100Percent_19, 9, 2, 1, 1)
        self.slideINaK_2 = QtWidgets.QSlider(self.tab_9)
        self.slideINaK_2.setMinimum(-200)
        self.slideINaK_2.setMaximum(100)
        self.slideINaK_2.setSingleStep(5)
        self.slideINaK_2.setPageStep(20)
        self.slideINaK_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideINaK_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideINaK_2.setTickInterval(25)
        self.slideINaK_2.setObjectName("slideINaK_2")
        self.gridLayout_5.addWidget(self.slideINaK_2, 7, 1, 1, 1)
        self.lblIKur_2 = QtWidgets.QLabel(self.tab_9)
        self.lblIKur_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIKur_2.setObjectName("lblIKur_2")
        self.gridLayout_5.addWidget(self.lblIKur_2, 4, 0, 1, 1)
        self.spinIKs_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinIKs_2.setMinimum(-200)
        self.spinIKs_2.setMaximum(100)
        self.spinIKs_2.setSingleStep(5)
        self.spinIKs_2.setObjectName("spinIKs_2")
        self.gridLayout_5.addWidget(self.spinIKs_2, 3, 3, 1, 1)
        self.slideINCX_2 = QtWidgets.QSlider(self.tab_9)
        self.slideINCX_2.setMinimum(-200)
        self.slideINCX_2.setMaximum(100)
        self.slideINCX_2.setSingleStep(5)
        self.slideINCX_2.setPageStep(20)
        self.slideINCX_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideINCX_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideINCX_2.setTickInterval(25)
        self.slideINCX_2.setObjectName("slideINCX_2")
        self.gridLayout_5.addWidget(self.slideINCX_2, 8, 1, 1, 1)
        self.lblIKr_2 = QtWidgets.QLabel(self.tab_9)
        self.lblIKr_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIKr_2.setObjectName("lblIKr_2")
        self.gridLayout_5.addWidget(self.lblIKr_2, 2, 0, 1, 1)
        self.lblINaL_2 = QtWidgets.QLabel(self.tab_9)
        self.lblINaL_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblINaL_2.setObjectName("lblINaL_2")
        self.gridLayout_5.addWidget(self.lblINaL_2, 6, 0, 1, 1)
        self.slideIKs_2 = QtWidgets.QSlider(self.tab_9)
        self.slideIKs_2.setMinimum(-200)
        self.slideIKs_2.setMaximum(100)
        self.slideIKs_2.setSingleStep(5)
        self.slideIKs_2.setPageStep(20)
        self.slideIKs_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideIKs_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIKs_2.setTickInterval(25)
        self.slideIKs_2.setObjectName("slideIKs_2")
        self.gridLayout_5.addWidget(self.slideIKs_2, 3, 1, 1, 1)
        self.slideIto_2 = QtWidgets.QSlider(self.tab_9)
        self.slideIto_2.setMinimum(-200)
        self.slideIto_2.setMaximum(100)
        self.slideIto_2.setSingleStep(5)
        self.slideIto_2.setPageStep(20)
        self.slideIto_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideIto_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIto_2.setTickInterval(25)
        self.slideIto_2.setObjectName("slideIto_2")
        self.gridLayout_5.addWidget(self.slideIto_2, 9, 1, 1, 1)
        self.spinINCX_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinINCX_2.setMinimum(-200)
        self.spinINCX_2.setMaximum(100)
        self.spinINCX_2.setSingleStep(5)
        self.spinINCX_2.setObjectName("spinINCX_2")
        self.gridLayout_5.addWidget(self.spinINCX_2, 8, 3, 1, 1)
        self.lblIto_2 = QtWidgets.QLabel(self.tab_9)
        self.lblIto_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIto_2.setObjectName("lblIto_2")
        self.gridLayout_5.addWidget(self.lblIto_2, 9, 0, 1, 1)
        self.label100Percent_16 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_16.setObjectName("label100Percent_16")
        self.gridLayout_5.addWidget(self.label100Percent_16, 3, 2, 1, 1)
        self.spinIK1_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinIK1_2.setMinimum(-200)
        self.spinIK1_2.setMaximum(100)
        self.spinIK1_2.setSingleStep(5)
        self.spinIK1_2.setObjectName("spinIK1_2")
        self.gridLayout_5.addWidget(self.spinIK1_2, 1, 3, 1, 1)
        self.slideICaL_2 = QtWidgets.QSlider(self.tab_9)
        self.slideICaL_2.setMinimum(-200)
        self.slideICaL_2.setMaximum(100)
        self.slideICaL_2.setSingleStep(5)
        self.slideICaL_2.setPageStep(20)
        self.slideICaL_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideICaL_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideICaL_2.setTickInterval(25)
        self.slideICaL_2.setObjectName("slideICaL_2")
        self.gridLayout_5.addWidget(self.slideICaL_2, 0, 1, 1, 1)
        self.lblIK1_2 = QtWidgets.QLabel(self.tab_9)
        self.lblIK1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblIK1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIK1_2.setObjectName("lblIK1_2")
        self.gridLayout_5.addWidget(self.lblIK1_2, 1, 0, 1, 1)
        self.spinIKr_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinIKr_2.setMinimum(-200)
        self.spinIKr_2.setMaximum(100)
        self.spinIKr_2.setSingleStep(5)
        self.spinIKr_2.setObjectName("spinIKr_2")
        self.gridLayout_5.addWidget(self.spinIKr_2, 2, 3, 1, 1)
        self.slideINaL_2 = QtWidgets.QSlider(self.tab_9)
        self.slideINaL_2.setMinimum(-200)
        self.slideINaL_2.setMaximum(100)
        self.slideINaL_2.setSingleStep(5)
        self.slideINaL_2.setPageStep(20)
        self.slideINaL_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideINaL_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideINaL_2.setTickInterval(25)
        self.slideINaL_2.setObjectName("slideINaL_2")
        self.gridLayout_5.addWidget(self.slideINaL_2, 6, 1, 1, 1)
        self.slideIK1_2 = QtWidgets.QSlider(self.tab_9)
        self.slideIK1_2.setMinimum(-200)
        self.slideIK1_2.setMaximum(100)
        self.slideIK1_2.setSingleStep(5)
        self.slideIK1_2.setPageStep(20)
        self.slideIK1_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideIK1_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIK1_2.setTickInterval(25)
        self.slideIK1_2.setObjectName("slideIK1_2")
        self.gridLayout_5.addWidget(self.slideIK1_2, 1, 1, 1, 1)
        self.label100Percent_13 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_13.setObjectName("label100Percent_13")
        self.gridLayout_5.addWidget(self.label100Percent_13, 2, 2, 1, 1)
        self.slideIKr_2 = QtWidgets.QSlider(self.tab_9)
        self.slideIKr_2.setMinimum(-200)
        self.slideIKr_2.setMaximum(100)
        self.slideIKr_2.setSingleStep(5)
        self.slideIKr_2.setPageStep(20)
        self.slideIKr_2.setOrientation(QtCore.Qt.Horizontal)
        self.slideIKr_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideIKr_2.setTickInterval(25)
        self.slideIKr_2.setObjectName("slideIKr_2")
        self.gridLayout_5.addWidget(self.slideIKr_2, 2, 1, 1, 1)
        self.lblICaL_2 = QtWidgets.QLabel(self.tab_9)
        self.lblICaL_2.setIndent(2)
        self.lblICaL_2.setObjectName("lblICaL_2")
        self.gridLayout_5.addWidget(self.lblICaL_2, 0, 0, 1, 1)
        self.spinICaL_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinICaL_2.setMinimum(-200)
        self.spinICaL_2.setMaximum(100)
        self.spinICaL_2.setSingleStep(5)
        self.spinICaL_2.setObjectName("spinICaL_2")
        self.gridLayout_5.addWidget(self.spinICaL_2, 0, 3, 1, 1)
        self.label100Percent_11 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_11.setObjectName("label100Percent_11")
        self.gridLayout_5.addWidget(self.label100Percent_11, 0, 2, 1, 1)
        self.label100Percent_12 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_12.setObjectName("label100Percent_12")
        self.gridLayout_5.addWidget(self.label100Percent_12, 1, 2, 1, 1)
        self.spinIf_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinIf_2.setMinimum(-200)
        self.spinIf_2.setMaximum(100)
        self.spinIf_2.setSingleStep(5)
        self.spinIf_2.setObjectName("spinIf_2")
        self.gridLayout_5.addWidget(self.spinIf_2, 4, 3, 1, 1)
        self.spinIto_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinIto_2.setMinimum(-200)
        self.spinIto_2.setMaximum(100)
        self.spinIto_2.setSingleStep(5)
        self.spinIto_2.setObjectName("spinIto_2")
        self.gridLayout_5.addWidget(self.spinIto_2, 9, 3, 1, 1)
        self.spinINaL_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinINaL_2.setMinimum(-200)
        self.spinINaL_2.setMaximum(100)
        self.spinINaL_2.setSingleStep(5)
        self.spinINaL_2.setObjectName("spinINaL_2")
        self.gridLayout_5.addWidget(self.spinINaL_2, 6, 3, 1, 1)
        self.label100Percent_14 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_14.setObjectName("label100Percent_14")
        self.gridLayout_5.addWidget(self.label100Percent_14, 5, 2, 1, 1)
        self.label100Percent_18 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_18.setObjectName("label100Percent_18")
        self.gridLayout_5.addWidget(self.label100Percent_18, 7, 2, 1, 1)
        self.lblIKs_2 = QtWidgets.QLabel(self.tab_9)
        self.lblIKs_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIKs_2.setObjectName("lblIKs_2")
        self.gridLayout_5.addWidget(self.lblIKs_2, 3, 0, 1, 1)
        self.label100Percent_17 = QtWidgets.QLabel(self.tab_9)
        self.label100Percent_17.setObjectName("label100Percent_17")
        self.gridLayout_5.addWidget(self.label100Percent_17, 6, 2, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_5, 4, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_17.addWidget(self.label_7, 1, 0, 1, 1)
        self.tabGeneral.addTab(self.tab_9, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.formLayout = QtWidgets.QFormLayout(self.tab_6)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.xaxis_mdl1_from = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.xaxis_mdl1_from.setMaximum(9999.0)
        self.xaxis_mdl1_from.setObjectName("xaxis_mdl1_from")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.xaxis_mdl1_from)
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.xaxis_mdl1_to = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.xaxis_mdl1_to.setMaximum(999999.0)
        self.xaxis_mdl1_to.setProperty("value", 1000.0)
        self.xaxis_mdl1_to.setObjectName("xaxis_mdl1_to")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.xaxis_mdl1_to)
        self.resetaxes_button = QtWidgets.QPushButton(self.tab_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resetaxes_button.setFont(font)
        self.resetaxes_button.setObjectName("resetaxes_button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.resetaxes_button)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem13)
        self.tabGeneral.addTab(self.tab_6, "")
        self.verticalLayout_3.addWidget(self.tabGeneral)
        self.cmdRun = QtWidgets.QPushButton(self.frameControls)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cmdRun.setFont(font)
        self.cmdRun.setObjectName("cmdRun")
        self.verticalLayout_3.addWidget(self.cmdRun)
        self.cmdReset = QtWidgets.QPushButton(self.frameControls)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cmdReset.setFont(font)
        self.cmdReset.setObjectName("cmdReset")
        self.verticalLayout_3.addWidget(self.cmdReset)
        self.label = QtWidgets.QLabel(self.frameControls)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.gridLayout_3.addWidget(self.frameControls, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1179, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.s1s2plot_ref1.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabGeneral.setCurrentIndex(0)
        self.slideIKr.valueChanged['int'].connect(self.spinIKr.setValue)
        self.slideINaK.valueChanged['int'].connect(self.spinINaK.setValue)
        self.slideIto.valueChanged['int'].connect(self.spinIto.setValue)
        self.slideICaL.valueChanged['int'].connect(self.spinICaL.setValue)
        self.slideIKs.valueChanged['int'].connect(self.spinIKs.setValue)
        self.slideINa.valueChanged['int'].connect(self.spinINa.setValue)
        self.slideINaL.valueChanged['int'].connect(self.spinINaL.setValue)
        self.slideINCX.valueChanged['int'].connect(self.spinINCX.setValue)
        self.slideIK1.valueChanged['int'].connect(self.spinIK1.setValue)
        self.slideIf.valueChanged['int'].connect(self.spinIf.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "induced Pluripotent Stem Cell-Derived Cardiomyocyte Maturity Evaluator (iMATURE)"))
        self.lblModel1.setText(_translate("MainWindow", "Model:"))
        self.lblAPDCaTModel1Ctrl.setText(_translate("MainWindow", "REF - APD: xxx ms // dV/dt_max: xxx mV/ms // CaT: xxx nM"))
        self.lblAPDCaTModel1Alt.setText(_translate("MainWindow", "Cell 1 - APD: xxx ms // dV/dt_max: xxx mV/ms // CaT: xxx nM"))
        self.lblAPDCaTModel1Alt_2.setText(_translate("MainWindow", "Cell 2 - APD: xxx ms // dV/dt_max: xxx mV/ms // CaT: xxx nM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Stimulus"))
        self.aad2_mdl1_top.setText(_translate("MainWindow", "Cell 2"))
        self.aad1_mdl1_top.setText(_translate("MainWindow", "Cell 1"))
        self.ref_mdl1_top.setText(_translate("MainWindow", "REF"))
        self.aad2_mdl1_bottom.setText(_translate("MainWindow", "Cell 2"))
        self.aad1_mdl1_bottom.setText(_translate("MainWindow", "Cell 1"))
        self.ref_mdl1_bottom.setText(_translate("MainWindow", "REF"))
        self.s1s2plot_ref1.setTabText(self.s1s2plot_ref1.indexOf(self.tab), _translate("MainWindow", "Output"))
        self.lblPrepacing1.setText(_translate("MainWindow", "Prepacing (# beats):"))
        self.lblStimDur1.setText(_translate("MainWindow", "Duration (ms):"))
        self.lblRate.setText(_translate("MainWindow", "Rate (bpm):"))
        self.lblShowbeats1.setText(_translate("MainWindow", "Output (# beats):"))
        self.label_4.setText(_translate("MainWindow", "Stim amplitude (uA/uF):"))
        self.lblNao1.setText(_translate("MainWindow", "<html><head/><body><p>[Na<span style=\" vertical-align:super;\">+</span>] (mmol/l): </p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "= Insert single value (60) or multiple values (60, 90, 120, 180, ...) ="))
        self.lblStimAmp1.setText(_translate("MainWindow", "Amplitude (%):"))
        self.txtRateModel1.setText(_translate("MainWindow", "60"))
        self.lblCao1.setText(_translate("MainWindow", "<html><head/><body><p>[Ca<span style=\" vertical-align:super;\">2+</span>] (mmol/l):</p></body></html>"))
        self.lblSettingsExtracellular1.setText(_translate("MainWindow", "Extracellular conditions:"))
        self.lblKo1.setText(_translate("MainWindow", "<html><head/><body><p>[K<span style=\" vertical-align:super;\">+</span>] (mmol/l):</p></body></html>"))
        self.lblSettingsStimulus1.setText(_translate("MainWindow", "Stimulus properties:"))
        self.label_5.setText(_translate("MainWindow", "Hyperpolarizing current (uA/uF):"))
        self.s1s2plot_ref1.setTabText(self.s1s2plot_ref1.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        self.label_11.setText(_translate("MainWindow", "Save generated plots into CSV file:"))
        self.export_1.setText(_translate("MainWindow", "Export Plot(s)"))
        self.label_13.setText(_translate("MainWindow", "Notes:"))
        self.label_14.setText(_translate("MainWindow", "Generated file is listed as: "))
        self.label_26.setText(_translate("MainWindow", "Time // Reference // Time // Cell 1 // Time // Cell 2"))
        self.label_9.setText(_translate("MainWindow", "iMATURE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."))
        self.s1s2plot_ref1.setTabText(self.s1s2plot_ref1.indexOf(self.tab_7), _translate("MainWindow", "Export"))
        self.label100Percent_9.setText(_translate("MainWindow", "100%"))
        self.label100Percent_7.setText(_translate("MainWindow", "100%"))
        self.lblINaK.setText(_translate("MainWindow", "INaK: -200%"))
        self.label100Percent.setText(_translate("MainWindow", "100%"))
        self.lblINCX.setText(_translate("MainWindow", "INCX: -200%"))
        self.lblINa.setText(_translate("MainWindow", "INa: -200%"))
        self.lblIto.setText(_translate("MainWindow", "Ito: -200%"))
        self.label100Percent_6.setText(_translate("MainWindow", "100%"))
        self.label100Percent_10.setText(_translate("MainWindow", "100%"))
        self.lblIKs.setText(_translate("MainWindow", "IKs: -200%"))
        self.lblINaL.setText(_translate("MainWindow", "INa,L: -200%"))
        self.label100Percent_5.setText(_translate("MainWindow", "100%"))
        self.lblIK1.setText(_translate("MainWindow", "IK1: -200%"))
        self.label100Percent_2.setText(_translate("MainWindow", "100%"))
        self.lblICaL.setText(_translate("MainWindow", "ICa,L: -200%"))
        self.label100Percent_3.setText(_translate("MainWindow", "100%"))
        self.label100Percent_4.setText(_translate("MainWindow", "100%"))
        self.lblIKr.setText(_translate("MainWindow", "IKr: -200%"))
        self.lblIKur.setText(_translate("MainWindow", "If: -200%"))
        self.label100Percent_8.setText(_translate("MainWindow", "100%"))
        self.label_24.setText(_translate("MainWindow", "Ion channel block:"))
        self.lblConcentration.setText(_translate("MainWindow", "<html><head/><body><p>Maturity (days):</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Maturity level: 20 - 80 days"))
        self.tabGeneral.setTabText(self.tabGeneral.indexOf(self.tab_5), _translate("MainWindow", "Cell 1"))
        self.label_25.setText(_translate("MainWindow", "Ion channel block:"))
        self.lblConcentration_3.setText(_translate("MainWindow", "<html><head/><body><p>Maturity (days):</p></body></html>"))
        self.lblINa_2.setText(_translate("MainWindow", "INa: -200%"))
        self.lblINCX_2.setText(_translate("MainWindow", "INCX: -200%"))
        self.label100Percent_15.setText(_translate("MainWindow", "100%"))
        self.label100Percent_20.setText(_translate("MainWindow", "100%"))
        self.lblINaK_2.setText(_translate("MainWindow", "INaK: -200%"))
        self.label100Percent_19.setText(_translate("MainWindow", "100%"))
        self.lblIKur_2.setText(_translate("MainWindow", "If: -200%"))
        self.lblIKr_2.setText(_translate("MainWindow", "IKr: -200%"))
        self.lblINaL_2.setText(_translate("MainWindow", "INa,L: -200%"))
        self.lblIto_2.setText(_translate("MainWindow", "Ito: -200%"))
        self.label100Percent_16.setText(_translate("MainWindow", "100%"))
        self.lblIK1_2.setText(_translate("MainWindow", "IK1: -200%"))
        self.label100Percent_13.setText(_translate("MainWindow", "100%"))
        self.lblICaL_2.setText(_translate("MainWindow", "ICa,L: -200%"))
        self.label100Percent_11.setText(_translate("MainWindow", "100%"))
        self.label100Percent_12.setText(_translate("MainWindow", "100%"))
        self.label100Percent_14.setText(_translate("MainWindow", "100%"))
        self.label100Percent_18.setText(_translate("MainWindow", "100%"))
        self.lblIKs_2.setText(_translate("MainWindow", "IKs: -200%"))
        self.label100Percent_17.setText(_translate("MainWindow", "100%"))
        self.label_7.setText(_translate("MainWindow", "Maturity level: 20 - 80 days"))
        self.tabGeneral.setTabText(self.tabGeneral.indexOf(self.tab_9), _translate("MainWindow", "Cell 2"))
        self.label_17.setText(_translate("MainWindow", "Set x-axes of:"))
        self.label_18.setText(_translate("MainWindow", "Model 1:"))
        self.label_19.setText(_translate("MainWindow", "From:"))
        self.label_20.setText(_translate("MainWindow", "To:"))
        self.resetaxes_button.setText(_translate("MainWindow", "Reset x-axes"))
        self.tabGeneral.setTabText(self.tabGeneral.indexOf(self.tab_6), _translate("MainWindow", "Options"))
        self.cmdRun.setText(_translate("MainWindow", "Run"))
        self.cmdReset.setText(_translate("MainWindow", "Reset Values"))
        self.label.setText(_translate("MainWindow", "v1.1.1 == Heijman\'s & Voigt\'s Labs == 2021"))
#from matplotlibwidget import MatplotlibWidget
#import Resource_rc

from . import MatplotlibWidget5
from . import Resource_rc5

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    #app = QtWidgets.QApplication(sys.argv)
    #MainWindow = QtWidgets.QMainWindow()
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
