import numpy as np

a = np.arange(1, 5, 0.5)
print(">>> ", a)
print(">>> ", a.dtype)
print(">>> ", a.astype(np.int32))
print("------------------------------------------------------------------------------------------")
a = np.array([[1, 2, 5], [6, 3, 4], [5, 6, 0]])
b = a.tolist()
print(">>> ", b)
print(">>> ", type(b))
print("------------------------------------------------------------------------------------------")
a = np.array(["1.2", "2.4", "3.1415"])
print(">>> ", a.itemsize * a.size)
print(">>> ", a.astype(np.float64))
