# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cognite/seismic/protos/persisted_trace.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cognite/seismic/protos/persisted_trace.proto',
  package='com.cognite.seismic',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,cognite/seismic/protos/persisted_trace.proto\x12\x13\x63om.cognite.seismic\"@\n\x0ePersistedTrace\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\r\n\x05trace\x18\x02 \x01(\x0c\x12\x0e\n\x06header\x18\x03 \x01(\x0c\x62\x06proto3'
)




_PERSISTEDTRACE = _descriptor.Descriptor(
  name='PersistedTrace',
  full_name='com.cognite.seismic.PersistedTrace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='com.cognite.seismic.PersistedTrace.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trace', full_name='com.cognite.seismic.PersistedTrace.trace', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header', full_name='com.cognite.seismic.PersistedTrace.header', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['PersistedTrace'] = _PERSISTEDTRACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersistedTrace = _reflection.GeneratedProtocolMessageType('PersistedTrace', (_message.Message,), {
  'DESCRIPTOR' : _PERSISTEDTRACE,
  '__module__' : 'cognite.seismic.protos.persisted_trace_pb2'
  # @@protoc_insertion_point(class_scope:com.cognite.seismic.PersistedTrace)
  })
_sym_db.RegisterMessage(PersistedTrace)


# @@protoc_insertion_point(module_scope)
