INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Process');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Task');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('SporadicTask');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('TriggeredTask');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('DataType');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('ConstructedProcess');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Signal');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('NativeFunction');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Implementation');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Implements');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Constructs');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Types');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Takes');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Writes');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Reads');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('FIFOSignal');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Input');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Output');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Description');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Communication');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Computation');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Storage');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Interface');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Structure');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('TimeDivisionMultiplexer');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('ComputationalTile');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Goal');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Throughput');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('StaticCyclicScheduler');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('FixedPriorityScheduler');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('CustomScheduler');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('RoundRobinScheduler');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('SYComb');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('SYPrefix');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('SDFComb');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('SDFPrefix');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('DEPrefix');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('DEValueComb');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('DETagComb');
INSERT OR IGNORE INTO `_allowed_types` (type_name) VALUES ('Unknown');

INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Process', 'Process');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Task', 'Task');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('SporadicTask', 'SporadicTask');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('SporadicTask', 'Task');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('SporadicTask', 'TriggeredTask');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('TriggeredTask', 'TriggeredTask');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('TriggeredTask', 'Task');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('DataType', 'DataType');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('ConstructedProcess', 'ConstructedProcess');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('ConstructedProcess', 'Process');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Signal', 'Signal');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('NativeFunction', 'NativeFunction');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Implementation', 'Implementation');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Implements', 'Implements');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Constructs', 'Constructs');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Types', 'Types');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Takes', 'Takes');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Writes', 'Writes');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Reads', 'Reads');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('FIFOSignal', 'FIFOSignal');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('FIFOSignal', 'Signal');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Input', 'Input');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Output', 'Output');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Description', 'Description');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Communication', 'Communication');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Computation', 'Computation');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Storage', 'Storage');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Interface', 'Interface');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Structure', 'Structure');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('TimeDivisionMultiplexer', 'TimeDivisionMultiplexer');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('TimeDivisionMultiplexer', 'Communication');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('ComputationalTile', 'ComputationalTile');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('ComputationalTile', 'Computation');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Goal', 'Goal');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Throughput', 'Throughput');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('Throughput', 'Goal');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('StaticCyclicScheduler', 'StaticCyclicScheduler');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('FixedPriorityScheduler', 'FixedPriorityScheduler');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('CustomScheduler', 'CustomScheduler');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('RoundRobinScheduler', 'RoundRobinScheduler');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('SYComb', 'SYComb');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('SYPrefix', 'SYPrefix');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('SDFComb', 'SDFComb');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('SDFPrefix', 'SDFPrefix');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('DEPrefix', 'DEPrefix');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('DEValueComb', 'DEValueComb');
INSERT OR IGNORE INTO `_refined_types_base` (type_name, refined_type_name) VALUES ('DETagComb', 'DETagComb');
