depends = ('ITKPyBase', 'ITKPath', 'ITKOptimizers', 'ITKFastMarching', 'ITKCommon', )
templates = (
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterISS2PPP2', True, 'itk::Image<signed short, 2>, itk::PolyLineParametricPath<2>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterIUC2PPP2', True, 'itk::Image<unsigned char, 2>, itk::PolyLineParametricPath<2>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterIUS2PPP2', True, 'itk::Image<unsigned short, 2>, itk::PolyLineParametricPath<2>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterIF2PPP2', True, 'itk::Image<float, 2>, itk::PolyLineParametricPath<2>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterID2PPP2', True, 'itk::Image<double, 2>, itk::PolyLineParametricPath<2>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterISS3PPP3', True, 'itk::Image<signed short, 3>, itk::PolyLineParametricPath<3>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterIUC3PPP3', True, 'itk::Image<unsigned char, 3>, itk::PolyLineParametricPath<3>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterIUS3PPP3', True, 'itk::Image<unsigned short, 3>, itk::PolyLineParametricPath<3>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterIF3PPP3', True, 'itk::Image<float, 3>, itk::PolyLineParametricPath<3>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterID3PPP3', True, 'itk::Image<double, 3>, itk::PolyLineParametricPath<3>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterISS4PPP4', True, 'itk::Image<signed short, 4>, itk::PolyLineParametricPath<4>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterIUC4PPP4', True, 'itk::Image<unsigned char, 4>, itk::PolyLineParametricPath<4>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterIUS4PPP4', True, 'itk::Image<unsigned short, 4>, itk::PolyLineParametricPath<4>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterIF4PPP4', True, 'itk::Image<float, 4>, itk::PolyLineParametricPath<4>'),
  ('ArrivalFunctionToPathFilter', 'itk::ArrivalFunctionToPathFilter', 'itkArrivalFunctionToPathFilterID4PPP4', True, 'itk::Image<double, 4>, itk::PolyLineParametricPath<4>'),
  ('IterateNeighborhoodOptimizer', 'itk::IterateNeighborhoodOptimizer', 'itkIterateNeighborhoodOptimizer', True),
  ('FunctionBase', 'itk::FunctionBase', 'itkFunctionBasePF2CVdouble2', False, 'itk::Point<float, 2>, itk::CovariantVector<double, 2>'),
  ('FunctionBase', 'itk::FunctionBase', 'itkFunctionBasePF3CVdouble3', False, 'itk::Point<float, 3>, itk::CovariantVector<double, 3>'),
  ('FunctionBase', 'itk::FunctionBase', 'itkFunctionBasePF4CVdouble4', False, 'itk::Point<float, 4>, itk::CovariantVector<double, 4>'),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionISS2CVdouble2float', False, ' itk::Image<signed short, 2>, itk::CovariantVector<double, 2>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionIUC2CVdouble2float', False, ' itk::Image<unsigned char, 2>, itk::CovariantVector<double, 2>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionIUS2CVdouble2float', False, ' itk::Image<unsigned short, 2>, itk::CovariantVector<double, 2>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionIF2CVdouble2float', False, ' itk::Image<float, 2>, itk::CovariantVector<double, 2>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionID2CVdouble2float', False, ' itk::Image<double, 2>, itk::CovariantVector<double, 2>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionISS3CVdouble3float', False, ' itk::Image<signed short, 3>, itk::CovariantVector<double, 3>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionIUC3CVdouble3float', False, ' itk::Image<unsigned char, 3>, itk::CovariantVector<double, 3>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionIUS3CVdouble3float', False, ' itk::Image<unsigned short, 3>, itk::CovariantVector<double, 3>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionIF3CVdouble3float', False, ' itk::Image<float, 3>, itk::CovariantVector<double, 3>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionID3CVdouble3float', False, ' itk::Image<double, 3>, itk::CovariantVector<double, 3>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionISS4CVdouble4float', False, ' itk::Image<signed short, 4>, itk::CovariantVector<double, 4>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionIUC4CVdouble4float', False, ' itk::Image<unsigned char, 4>, itk::CovariantVector<double, 4>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionIUS4CVdouble4float', False, ' itk::Image<unsigned short, 4>, itk::CovariantVector<double, 4>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionIF4CVdouble4float', False, ' itk::Image<float, 4>, itk::CovariantVector<double, 4>, float '),
  ('ImageFunction', 'itk::ImageFunction', 'itkImageFunctionID4CVdouble4float', False, ' itk::Image<double, 4>, itk::CovariantVector<double, 4>, float '),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionISS2float', True, 'itk::Image<signed short, 2>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionIUC2float', True, 'itk::Image<unsigned char, 2>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionIUS2float', True, 'itk::Image<unsigned short, 2>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionIF2float', True, 'itk::Image<float, 2>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionID2float', True, 'itk::Image<double, 2>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionISS3float', True, 'itk::Image<signed short, 3>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionIUC3float', True, 'itk::Image<unsigned char, 3>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionIUS3float', True, 'itk::Image<unsigned short, 3>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionIF3float', True, 'itk::Image<float, 3>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionID3float', True, 'itk::Image<double, 3>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionISS4float', True, 'itk::Image<signed short, 4>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionIUC4float', True, 'itk::Image<unsigned char, 4>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionIUS4float', True, 'itk::Image<unsigned short, 4>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionIF4float', True, 'itk::Image<float, 4>, float'),
  ('PhysicalCentralDifferenceImageFunction', 'itk::PhysicalCentralDifferenceImageFunction', 'itkPhysicalCentralDifferenceImageFunctionID4float', True, 'itk::Image<double, 4>, float'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionISS2', True, 'itk::Image<signed short, 2>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionIUC2', True, 'itk::Image<unsigned char, 2>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionIUS2', True, 'itk::Image<unsigned short, 2>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionIF2', True, 'itk::Image<float, 2>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionID2', True, 'itk::Image<double, 2>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionISS3', True, 'itk::Image<signed short, 3>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionIUC3', True, 'itk::Image<unsigned char, 3>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionIUS3', True, 'itk::Image<unsigned short, 3>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionIF3', True, 'itk::Image<float, 3>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionID3', True, 'itk::Image<double, 3>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionISS4', True, 'itk::Image<signed short, 4>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionIUC4', True, 'itk::Image<unsigned char, 4>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionIUS4', True, 'itk::Image<unsigned short, 4>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionIF4', True, 'itk::Image<float, 4>'),
  ('SingleImageCostFunction', 'itk::SingleImageCostFunction', 'itkSingleImageCostFunctionID4', True, 'itk::Image<double, 4>'),
  ('SpeedFunctionPathInformation', 'itk::SpeedFunctionPathInformation', 'itkSpeedFunctionPathInformationPD2', True, 'itk::Point<double, 2>'),
  ('SpeedFunctionPathInformation', 'itk::SpeedFunctionPathInformation', 'itkSpeedFunctionPathInformationPD3', True, 'itk::Point<double, 3>'),
  ('SpeedFunctionPathInformation', 'itk::SpeedFunctionPathInformation', 'itkSpeedFunctionPathInformationPD4', True, 'itk::Point<double, 4>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterISS2PPP2', True, 'itk::Image<signed short, 2>, itk::PolyLineParametricPath<2>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterIUC2PPP2', True, 'itk::Image<unsigned char, 2>, itk::PolyLineParametricPath<2>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterIUS2PPP2', True, 'itk::Image<unsigned short, 2>, itk::PolyLineParametricPath<2>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterIF2PPP2', True, 'itk::Image<float, 2>, itk::PolyLineParametricPath<2>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterID2PPP2', True, 'itk::Image<double, 2>, itk::PolyLineParametricPath<2>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterISS3PPP3', True, 'itk::Image<signed short, 3>, itk::PolyLineParametricPath<3>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterIUC3PPP3', True, 'itk::Image<unsigned char, 3>, itk::PolyLineParametricPath<3>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterIUS3PPP3', True, 'itk::Image<unsigned short, 3>, itk::PolyLineParametricPath<3>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterIF3PPP3', True, 'itk::Image<float, 3>, itk::PolyLineParametricPath<3>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterID3PPP3', True, 'itk::Image<double, 3>, itk::PolyLineParametricPath<3>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterISS4PPP4', True, 'itk::Image<signed short, 4>, itk::PolyLineParametricPath<4>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterIUC4PPP4', True, 'itk::Image<unsigned char, 4>, itk::PolyLineParametricPath<4>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterIUS4PPP4', True, 'itk::Image<unsigned short, 4>, itk::PolyLineParametricPath<4>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterIF4PPP4', True, 'itk::Image<float, 4>, itk::PolyLineParametricPath<4>'),
  ('SpeedFunctionToPathFilter', 'itk::SpeedFunctionToPathFilter', 'itkSpeedFunctionToPathFilterID4PPP4', True, 'itk::Image<double, 4>, itk::PolyLineParametricPath<4>'),
)
