#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['reportengine',
 'reportengine.styles',
 'reportengine.templates',
 'reportengine.tests']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['jinja2',
 'ruamel_yaml',
 'matplotlib',
 'pandas',
 'pygments',
 'blessings',
 'curio']

extras_require = \
{'test': ['pytest', 'hypothesis']}

setup(name='reportengine',
      version='0.30.dev0',
      description='Reportengine: A fremework to organize data pypelines.',
      author='Zahari Kassabov',
      author_email='zk261@cam.ac.uk',
      url='https://github.com/NNPDF/reportengine/',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
     )
