
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-10T19:44:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "58ecdaa1e114161bc800731cd33d0e48f3544421",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
