# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61968/metering/Meter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61968.metering import EndDevice_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61968_dot_metering_dot_EndDevice__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/protobuf/cim/iec61968/metering/Meter.proto',
  package='zepben.protobuf.cim.iec61968.metering',
  syntax='proto3',
  serialized_options=b'\n)com.zepben.protobuf.cim.iec61968.meteringP\001\252\002%Zepben.Protobuf.CIM.IEC61968.Metering',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1zepben/protobuf/cim/iec61968/metering/Meter.proto\x12%zepben.protobuf.cim.iec61968.metering\x1a\x35zepben/protobuf/cim/iec61968/metering/EndDevice.proto\"E\n\x05Meter\x12<\n\x02\x65\x64\x18\x01 \x01(\x0b\x32\x30.zepben.protobuf.cim.iec61968.metering.EndDeviceBU\n)com.zepben.protobuf.cim.iec61968.meteringP\x01\xaa\x02%Zepben.Protobuf.CIM.IEC61968.Meteringb\x06proto3'
  ,
  dependencies=[zepben_dot_protobuf_dot_cim_dot_iec61968_dot_metering_dot_EndDevice__pb2.DESCRIPTOR,])




_METER = _descriptor.Descriptor(
  name='Meter',
  full_name='zepben.protobuf.cim.iec61968.metering.Meter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ed', full_name='zepben.protobuf.cim.iec61968.metering.Meter.ed', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=216,
)

_METER.fields_by_name['ed'].message_type = zepben_dot_protobuf_dot_cim_dot_iec61968_dot_metering_dot_EndDevice__pb2._ENDDEVICE
DESCRIPTOR.message_types_by_name['Meter'] = _METER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Meter = _reflection.GeneratedProtocolMessageType('Meter', (_message.Message,), {
  'DESCRIPTOR' : _METER,
  '__module__' : 'zepben.protobuf.cim.iec61968.metering.Meter_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.cim.iec61968.metering.Meter)
  })
_sym_db.RegisterMessage(Meter)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
